### ISSUE TITLE
Onboarding Tracker for FLYTE

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#16]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion.

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:**  Incubation
**--Company Sponsor (Full Legal Name):**
**--Jurisdiction of Incorporation:**
**--Address:**
**--Project Sponsor Contact:** Ketan Umare and George Snelling
**--Technical Contact:** Ketan Umare 
**--Legal Contact:**
**--TAC Sponsor:**
**--TAC Approval Date:** 02/25/2021
**--Project in SFDC:** https://linuxfoundation.lightning.force.com/lightning/r/Project__c/a092M00001IkXEBQA3/view
**--Project License:** Apache 2.0
**--Project Presentation:** https://drive.google.com/file/d/1rwAxVd71Ss9AiGVGFs6EExV8uB9JpaE4/view?usp=sharing
**--Project Proposal per LF AI & Data:** https://github.com/lfai/proposing-projects/blob/master/proposals/flyte.adoc
**--Project Artwork:** https://artwork.lfaidata.foundation/projects/flyte/

**LICENSING** [Completed]

 - [x] (ED) Project license exists and is OSI-approved // **Confirmed - Apache 2.0**
 - [x] (ED) Proposed license inline with umbrella's IP Policy // **Confirmed**
 - [x] (ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // **Confirmed - no issue**
 - [x] (ED) Determine known components/dependencies not under compatible license // **Confirmed - no issue**

**CONTRIBUTION**

 - [x] (ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco // **Confirmed**
 - [x] (ED) Share/Discuss Project Charter Template and Finalize with Project (update New Projects Onboarding with Legal Status Tracking) // **Completed**
 - [x] (ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project (update New Projects Onboarding with Legal Status Tracking) // **Completed**
- [x]  (ED) Verify CII Badge (Silver) link and passing status // **Ongoing with Ketan** https://bestpractices.coreinfrastructure.org/en/projects/4670 --Completed 11/08/21

**PROJECT ASSETS**

 - [x] (ED) Domain name confirmation // If no domain is registered, then one is to be purchased // If one exists, it must be transferred using https://jira.linuxfoundation.org/servicedesk/customer/kb/view/28485232 // Reference: https://confluence.linuxfoundation.org/display/LID/Domain+Registration+and+Transfers |
 - [x] (ED) Logos confirmation // If no logo exists, request creation via Creative Services Jira ticket // https://artwork.lfaidata.foundation/projects/flyte/
 - [x] (ED) Post project logos to GitHub Artwork repo and save in Project Logos in LF internal Google Drive folder
 - [x] (ED) Project website confirmation // If no website exists (as noted above), request a new website creation via Creative Services (Include request for project lead to be added as authorized user for Word Press for future website updates, requires -name/email of authorized user) 
 - [x] (ED) Add name/email of authorized user for Word Press and future website updates to LF internal tracking

**TAC & GOVERNING BOARD REVIEW** [Completed]

 - [x] (ED) Provide project proposal process/template to project sponsor // **Confirmed**
 - [x] (ED) Confirm/Schedule presentation date during TAC meeting - Add to TAC Mtg Agenda Tracking // **Confirmed**
 - [x] (ED) Review and confirm final proposal and presentation deck // **Confirmed**
 - [x] (ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info // **Confirmed**
 - [x] (ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members // **Confirmed**
 - [x] (PM) Verify TAC minutes with project TAC vote results //  **Confirmed**

**INFRASTRUCTURE**  [Completed]

 - [x] (ED) Update Github proposal to show project accepted // **Confirmed**
 - [x] (ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership // **Completed**
 - [x] (ED) Migrate code repository to new GH org // **Completed**
 - [x] (ED) Add project to LF AI & Data landscape and mark it as an LF AI & Data project // **Completed**
 - [x] (ED) Add logo of company donating project to LF AI & Data landscape // **Completed**

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under LF AI Groups.io
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration, if any - **N/A**
- [x] (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project  - **Not requested**
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project - **Not requested**
- [x] (PM)Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LF Insights dashboard, then submit Jira for request - **Jira submitted: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-4250**
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) - N/A
- [x] (PM) Confirm completion of Technical Project Getting Started Checklist and annual reviews with TAC sponsor and TAC - Tracked within TAC

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) - **Jira submitted: https://jira.linuxfoundation.org/browse/LP-7191**
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services ticket required (Ref LP-6711) - **Jira submitted: https://jira.linuxfoundation.org/browse/LP-7192**
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) 
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts -**Will need to transfer (post announcement) http://flyte-org.slack.com/ and Twitter account**

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects and also planned through Software Freedom Law Center for Graduate level projects - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649)
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
Hello All -- I'll be kicking off upcoming operations tasks on 03/01/21. 

Welcome Flyte team and please expect an onboarding email with more details/resources next week.

**Comment by jzcardoso** [comment]
@kumare3  As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the 'flyte-org.slack.com' workspace? Please confirm when complete.

**Comment by kumare3** [comment]
@jzcardoso done! please confirm when you receive it

**Comment by jzcardoso** [comment]
@kumare3 thanks for the quick response. Just as soon as I hear back from our team doing the set up I'll let you know that we are all good.

**Comment by jzcardoso** [comment]
@kumare3 We are set with the Slack access for LFX Insights. If anything further is needed we will let you know. Thanks.

**Comment by kumare3** [comment]
@jzcardoso So I just checked the LFX dashboard, it looks awesome. I had one question, it currently shows only one Flyte - repo, which is actually just a documentation repo. How can we get all our repos into this dashboard. That will really help the community

**Comment by jzcardoso** [comment]
@Ketan Umare ***@***.***> Great question. You can always request
more repos to be added by creating a ticket via our Jira Service Desk, the
LFX Insights section is found here:
https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/group/54.

If you have the full list of repos now I can add it in the current ticket,
otherwise you can submit a ticket anytime.

Thank you,
Jacqueline

Jacqueline Z Cardoso (Serafin)
Program Manager
The Linux Foundation
+1 (415) 676-1127 (m)
***@***.***
Regular Hours: 6am-3pm PT

**Comment by kumare3** [comment]
Sure here are the repos that we definitely want to be tracked, we will be adding a few more repos in the future

https://github.com/flyteorg/flyteadmin
https://github.com/flyteorg/flytepropeller
https://github.com/flyteorg/flytekit
https://github.com/flyteorg/flyteplugins
https://github.com/flyteorg/flyteidl
https://github.com/flyteorg/flytecopilot
https://github.com/flyteorg/flytestdlib
https://github.com/flyteorg/datacatalog
https://github.com/flyteorg/flyteconsole
https://github.com/flyteorg/flytecopilot
https://github.com/flyteorg/flytectl
https://github.com/flyteorg/flytekit-python-template

**Comment by kumare3** [comment]
@jzcardoso I do so the 12 repositories in the landing page, but not actual in the details page for Flyte - https://insights.lfx.linuxfoundation.org/projects/lfai%2Fflyte/dashboard
Is there something else I need to do?

**Comment by jzcardoso** [comment]
@kumare3 the ticket has not closed yet so the work is still in progress. Once it is closed we will cross off that item from our checklist.

**Comment by jzcardoso** [comment]
@kumare3 I hope all is well with you. I see that the project is now at 91% for the CII Badging which is great. Do you have an estimate for when you think the project will be able to attain 100% passing? We will need to track this per the incubation project requirements and to close out the onboarding of the project. Thanks.

**Comment by kumare3** [comment]
ohh I thought this is not required for the project to be incubating. Let me review this and get back to you. We should be 100% soon

**Comment by kumare3** [comment]
@jzcardoso also we want to add couple more repos to the tracker list
https://github.com/flyteorg/flytekit-java
https://github.com/flyteorg/boilerplate

**Comment by jzcardoso** [comment]
@kumare3 For any new repos that need to be added you will need to submit a ticket here: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4

**Comment by jzcardoso** [comment]
Hello @kumare3 -- Can you please provide an update on the pending CII Badging status? Can you please confirm when you have this completely wrapped up so we can close out this final item?

**Comment by kumare3** [comment]
@jzcardoso I think I had completely misunderstood the requirement. Just completed it. The Gold and Silver certifications are not fully complete yet https://bestpractices.coreinfrastructure.org/en/projects/4670

**Comment by jzcardoso** [comment]
@kumare3 Thanks for confirming the completion for the best practices badge. The Gold and Silver are not required for Incubation so you are good to go for now. Thanks again!
