### ISSUE TITLE
Onboarding Tracker for Datashim

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#17]
**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation 
**--Company Sponsor (Full Legal Name):** IBM
**--Project Sponsor Contact:** Jim Spohrer
**--Technical Contact:** Yiannis Gkoufas
**--Legal Contact:** 
**--TAC Sponsor:** Jim Spohrer 
**--TAC Approval Date:** 01/14/2021
**--Project License:** Apache 2.0
**--Project Presentation:** https://docs.google.com/presentation/d/1iklxG0wfDzYoDQLJFdbxZz5QWuYU4jjFy00s4JcSKz8/edit?usp=sharing 
**--Project Proposal per LF AI & Data:** https://github.com/lfai/proposing-projects/blob/master/proposals/dataset-lifecycle-framework.md
**--Project Artwork:** In progress LP-7064

**LICENSING** [Completed]

 - [x] (ED) Project license exists and is OSI-approved
 - [x] (ED) Proposed license inline with umbrella's IP Policy
 - [x] (ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
 - [x] (ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

 - [x]  (ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
 - [x]  (ED) Share/Discuss Project Charter Template and Finalize with Project 
 - [x]  (ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project (update New Projects Onboarding with Legal Status Tracking) 
 - [x]  (ED) Verify CII Badge (Silver) link and passing status // https://bestpractices.coreinfrastructure.org/en/projects/4821 -- Verified passing status on 11/09/21

**PROJECT ASSETS**

 - [x]  (ED) Domain name confirmation // **datashim.io** 
 - [x]  (ED) Logos confirmation 
 - [x]  (ED) Post project logos to GitHub Artwork repo and save in Project Logos in LF internal Google Drive folder
 - [x]  (ED) Project website confirmation // **LP-7219**
 - [x]  (ED) Add name/email of authorized user for Word Press and future website updates to LF internal tracking

**TAC & GOVERNING BOARD REVIEW** [Completed]

 - [x]  (ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
 - [x]  (ED) Confirm/Schedule presentation date during TAC meeting - Add to TAC Mtg Agenda Tracking
 - [x]  (ED) Review and confirm final proposal and presentation deck
 - [x]  (ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
 - [x]  (ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
 - [x]  (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE** [Completed]

 - [x]  (ED) Update Github proposal to show project accepted
 - [x]  (ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
 - [x]  (ED) Migrate code repository to new GH org 
 - [x]  (ED) Add project to LF AI & Data landscape and mark it as an LF AI & Data project 
 - [x]  (ED) Add logo of company donating project to LF AI & Data landscape

**OPERATIONS**

 - [x]  (PM) Post final technical charter to GH Project Charters repo and ensure it is saved in LF internal Projects Google Drive folder
 - [x]  (PM) Add project to Current Projects section on LF AI & Data wiki 
 - [x]  (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under LF AI Groups.io
 - [x]  (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
 - [x]  (PM) Set project lead as moderator for mail lists as applicable for ongoing management
 - [x]  (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
 - [x]  (PM) Send onboarding email with next steps info and resources - Includes Technical Getting Started Checklist 
 - [x]  (PM) Set up other misc collaboration, if any - N/A
 - [x]  (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project - Not requested
 - [x]  (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project - Not requested
 - [x]  (PM)Create new tab for project in LF AI & Data Tracking to have project added to LF Insights dashboard, then submit Jira for request - **Jira: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-4325**
 - [x]  (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting
 - [x]  (PM) Include update on new project in upcoming GB meeting agenda
 - [x]  (PM) Update "LF AI & Data Getting Involved Guide" deck 
 - [x]  (PM) Update "LF AI & Data Overview" deck 
 - [x]  (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on LF AI & Data GH presentations repo 

**GOVERNANCE**

 - [x]  (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) - N/A
 - [x]  (PM) Confirm completion of Technical Project Getting Started Checklist and annual reviews with TAC sponsor and TAC - Tracked within TAC

**MARKETING**

 - [x]  (PM) Update LF AI & Data Timeline with new project - Creative Services ticket required (Ref LP- 6341) - Save updated file in internal LF AI & Data G Drive and on LF AI & Data GH - Jira: https://jira.linuxfoundation.org/browse/LP-7220
 - [x]  (PM) Build landing page on LF AI & Data website and add to All Projects section - Creative Services ticket required (Ref LP-6711) - **Jira: https://jira.linuxfoundation.org/browse/LP-7221**
 - [x]  (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal LF AI & Data PR/Comms tracker - **Jacqueline drafted under DLF name, Carly to update/complete under new name**
 - [x]  (Mktg) Add project spotlight for future publishing in internal LF AI & Data PR/Comms tracker
 - [x]  (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable - **IBM only**
 - [x]  (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)
 - [x]  (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - **None included in proposal**
 
**LEGAL FOLLOW UP**

 - [x]  (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal LF AI & Data tracker
 - [x]  (PM) Confirm export control filings are done through Steve W. for all projects and also planned through Software Freedom Law Center for Graduate level projects - Add to internal LF AI & Data tracker
 - [x]  (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal LF AI & Data tracker

**Comment by jzcardoso** [comment]
@CarlyLF - This announcement was previously drafted under the original project name so you will just need to adjust for the naming.

@YiannisGkoufas - Related to the PM items, many were previously done under the original name so I will be going back through and adjusting for the naming change.

**Comment by jzcardoso** [comment]
@YiannisGkoufas As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the 'flyte-org.slack.com' workspace? Please confirm when complete.

**Comment by jzcardoso** [comment]
@YiannisGkoufas  I hope all is well with you. I see that the project is now at 78% for the CII Badging which is great. Do you have an estimate for when you think the project will be able to attain 100% passing? We will need to track this per the incubation project requirements and to close out the onboarding of the project. Thanks.

**Comment by YiannisGkoufas** [comment]
Hi @jzcardoso will be on vacations the next 2 weeks, but I believe by the end of August the badge would be 100% completed!

**Comment by jzcardoso** [comment]
@YiannisGkoufas Thanks for the update, that timeframe works. Have a good vacation!

**Comment by jzcardoso** [comment]
Hello @YiannisGkoufas, I hope you are doing well. Checking in the CII Badging status. Looks like you are almost complete! Can you please confirm when you have this completely wrapped up so we can close out this final item? Thanks in advance for your help and congrats on the great work!

**Comment by jzcardoso** [comment]
Hello @YiannisGkoufas -- Can you please provide us with an update on the CII Badging status. Can you please confirm when you have this completely wrapped up so we can close out this final item?

**Comment by YiannisGkoufas** [comment]
Apologies I missed that @jzcardoso I just managed to close the final item obtained the badge.

**Comment by jzcardoso** [comment]
@YiannisGkoufas That's great to hear, thanks for the update. And congrats on the badging!
