### ISSUE TITLE
Onboarding Tracker for RosaeNLG

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#18]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

**TECHNICAL PROJECT DETAILS**

--Maturity Level Proposed: Sandbox
--Company Sponsor (Full Legal Name):
--Jurisdiction of Incorporation:
--Address:
--Project Sponsor Contact:
--Technical Contact: Ludan Stoecklé - ludan.stoeckle@gmail.com
--Legal Contact:
--TAC Sponsor: Jamil Chawki <jamil.chawki@orange.com>
--TAC Approval Date: 03/11/2021
--Project in SFDC:
--Project License: Apache 2.0
--Project Presentation: https://drive.google.com/file/d/1gZTzJCGXku9s9SumwLaVAUM5MIBh3X4_/view?usp=sharing
--Project Proposal per LF AI & Data: https://github.com/lfai/proposing-projects/blob/master/proposals/RosaeNLG.adoc
--Project Artwork: **ongoing**

**LICENSING**

- [x] (ED) Project license exists and is OSI-approved 
- [x] (ED) Proposed license inline with umbrella's IP Policy 
- [x] (ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // **ongoing**
- [x] (ED) Determine known components/dependencies not under compatible license // **ongoing**

**CONTRIBUTION**

- [x] (ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (ED) Share/Discuss Project Charter Template and Finalize with Project 
- [x] (ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project
- [x] (ED) Verify CII Badge (Passing) link and passing status

**PROJECT ASSETS**

- [x] (ED) Domain name confirmation // **rosaenlg.org  - to be transferred  -- IT-21698**
- [x] (ED) Logos confirmation // If logos exist post to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (ED) Project website confirmation/tracking // If website exists Add name/email of authorized user for future website updates 
to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (ED) Review and confirm final proposal and presentation deck
- [x] (ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (ED) Update Github proposal to show project accepted
- [x] (ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (ED) Migrate code repository to new GH org
- [x] (ED) Add project to LF AI & Data landscape and mark it as an LF AI & Data project
- [x] (ED) Add logo of company donating project to LF AI & Data landscape **n/a**

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo] (https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei) **-- Pending charter**
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki](https://wiki.lfaidata.foundation/) 
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under LF AI Groups.io 
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist 
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project --None requested
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LF Insights dashboard, then submit Jira for request **--Jira: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-4423**
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide] (https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck 
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) **--Jira: https://jira.linuxfoundation.org/browse/LP-7251**
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services ticket required (Ref LP-6711) **--Jira: https://jira.linuxfoundation.org/browse/LP-7252**
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts **--Will need to provide admin access for Meetup, Slack, Medium, LinkedIn accts** 

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)

- [x] (PM) Confirm export control filings are done through Steve W. for all projects and also planned through Software Freedom Law Center for Graduate level projects - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649)

- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
@ludans Welcome to the LF AI & Data Foundation! You should have in your inbox an onboarding email to review which covers resources and initial info on joining the foundation. I'll be working on the Program Management and Operations tasks in our onboarding and will be circling back next week once we have a few more details ready to go (such as logo, legal, etc.). 

As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the RosaeNLG workspace? Even though you noted in your proposal it is not used much we will go ahead and have it added to the tool. You can check out the tool here: https://insights.lfx.linuxfoundation.org/projects/lfai-f

**Comment by ludans** [comment]
- reference artwork pushed here: https://github.com/RosaeNLG/rosaenlg/tree/master/packages/rosaenlg-doc/artwork
- dev-analytics-bot@linuxfoundation.org added in RosaeNLG workspace

please tell me when I have to work/provide info on any topic

**Comment by ibrahimhaddad** [comment]
> * reference artwork pushed here: https://github.com/RosaeNLG/rosaenlg/tree/master/packages/rosaenlg-doc/artwork
> * [dev-analytics-bot@linuxfoundation.org](mailto:dev-analytics-bot@linuxfoundation.org) added in RosaeNLG workspace
> 
> please tell me when I have to work/provide info on any topic

Hi @ludans, no action is needed. Here's the final artwork for the project: https://artwork.lfaidata.foundation/projects/rosaenlg/.
I've also added it here https://github.com/RosaeNLG/artwork as we do with all of our hosted projects.
Thank you.
