### ISSUE TITLE
Onboarding Tracker for Substra

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#19]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation
**--Company Sponsor (Full Legal Name):** Substra Foundation 
**--Jurisdiction of Incorporation:** France
**--Address:**
**--Project Sponsor Contact:** Ibrahim Haddad
**--Technical Contact:** Eric Boniface <eric.boniface@substra.org>
**--Legal Contact:** Eric Boniface <eric.boniface@substra.org>
**--TAC Sponsor:** Ibrahim Haddad
**--TAC Approval Date:** 03/25/2021
**--Project in SFDC:** https://linuxfoundation.lightning.force.com/lightning/r/Account/0012M00002H3jZzQAJ/view
**--Project License:** Apache 2.0
**--Project Presentation:** https://drive.google.com/drive/u/1/folders/1V0088tbl6VtvLcu26O9OwnJ6S1HpGGTa
**--Project Proposal per LF AI & Data:** https://github.com/lfai/proposing-projects/blob/master/proposals/substra.md 
**--Project Artwork:** 

**LICENSING**

- [x] (ED) Project license exists and is OSI-approved 
- [x] (ED) Proposed license inline with umbrella's IP Policy 
- [x] (ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // **ongoing**
- [x] (ED) Determine known components/dependencies not under compatible license // **ongoing**

**CONTRIBUTION**

- [x] (ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The technical charter is tailored for LF AI & Data - Copy is to be created for each project - The technical charter will always need the following information dropped in place: the short name of the project (where [Community Name] appears); a short mission statement following the "The mission of the project is to..." convention; and confirmation of the specific licenses in Section 7 for code and/or data (many projects will not need data and this subjection regarding data licensing in those cases can be removed) 
- [x] (ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The trademark assignment agreement is also tailored for LF AI & Data - Copy is to be created for each project - As for the trademark agreement, we will entertain changes from companies contributing projects but we ask that the following be made clear to project sponsors: the contribution agreement was prepared to be a balanced agreement -- A large number of our members sign this as drafted; and extensive comments and revisions to the agreement will involve time which will slow down a project's start with LF AI & Data
- [x] (ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en)(Silver) link and passing status --in progress, currently 97% (https://bestpractices.coreinfrastructure.org/en/projects/6712)

**PROJECT ASSETS**

- [x] (ED) Logos confirmation // If no logo exists, request creation via Creative Services Jira ticket (All versions required: horizontal, vertical, icon in black/white/color in PNG and SVG)
- [x] (ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (ED) Domain name confirmation // **waiting on substra team to provide transfer codes and dns zone files**
- [x] (ED) Project website confirmation // **we have a ticket with create team to build the site -  ticket:LC-856**
- [x] (ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (ED) Review and confirm final proposal and presentation deck
- [x] (ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (ED) Update Github proposal to show project accepted
- [x] (ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (ED) Migrate code repository to new GH org
- [x] (ED) Add project to LF AI & Data landscape and mark it as an LF AI & Data project
- [x] (ED) Add logo of company donating project to LF AI & Data landscape

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/) 
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under LF AI Groups.io 
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration, if any - N/A
- [x] (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project -- None requested at time of onboarding
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project **--Pending response to onboarding email -- None requested at time of onboarding
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LF Insights dashboard, then submit Jira for request --Jira Completed: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-5753**
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details)
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck 
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations)
- [x] (PM) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts -Will need transfers for Slack, Twitter, LinkedIn - Sent project lead info on next steps required on 07/26/21, Erin will work with project lead to complete -- Accounts were moved to other org thus no transfers to LF at this time, project can choose to create new accounts at a later time and can transfer admin rights then.

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) --N/A
- [x] (PM) Confirm completion of Technical Project Getting Started Checklist and annual reviews with TAC sponsor and TAC --Tracked via TAC/Sponsor

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) **--Jira: https://jira.linuxfoundation.org/browse/LP-7594**
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services ticket required (Ref LP-6711) **--Jira: https://jira.linuxfoundation.org/browse/LP-7596**
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) --Published 7/14/21

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ + Planned through Software Freedom Law Center for Graduate level projects, add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) **--Jira pending: https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-624 
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
I'll be working on PM/Ops items starting next week while the final project naming and logo are solidified.

**Comment by jzcardoso** [comment]
Project needs to do the following for LFX Insights and Security:

1. LFX Insights -- As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the the openlineage workspace? Please confirm when complete so that our product team can add the project.

2. LFX Security -- We would like to include your project in the LFX Security tool. As the project lead, please take a few minutes to submit the request for your project by visiting the LFX Security page, click on "Secure My Project" on the top right, and follow the prompts. The process takes only a few minutes and once it is approved it will be added along with the other LF AI & Data Foundation projects. Overtime if you want to add additional repos or for general questions you can always submit a ticket here. Please let us know when this has requested.

**Comment by jzcardoso** [comment]
@ibrahimhaddad I've gone through and completed the items that were pending a logo and I've updated the tracking for the PM/Ops/Marketing items.

**Comment by jzcardoso** [comment]
@camillemarini -Please review the following items which we need to work on as part of the onboarding for Substra:

1. LFX Insights -- As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the the substra workspace? Please confirm when complete so that our product team can add the project.
2. LFX Security -- We would like to include your project in the LFX Security tool. As the project lead, please take a few minutes to submit the request for your project by visiting the LFX Security page, click on "Secure My Project" on the top right, and follow the prompts. The process takes only a few minutes and once it is approved it will be added along with the other LF AI & Data Foundation projects. Overtime if you want to add additional repos or for general questions you can always submit a ticket here. Please let us know when this has requested.

**Comment by jzcardoso** [comment]
@ibrahimhaddad -- There are two items I see pending which may or may not be held prior to the announcement: Domain/Website, CII Badge. How would you like to proceed? 

The announcement draft was previously reviewed and approved by the Substra team. We just need to determine a target publishing date.

All other open items are in motion and will complete in the next few weeks as tickets close.

**Comment by jzcardoso** [comment]
@camillemarini  We need your help with the following items to move further in completing the various onboarding tasks required. Please review and complete the action items noted below: 

LFX Insights -- As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the the substra workspace? Please confirm when complete so that our product team can add the project.

LFX Security -- We would like to include your project in the LFX Security tool. As the project lead, please take a few minutes to submit the request for your project by visiting the LFX Security page, click on "Secure My Project" on the top right, and follow the prompts. The process takes only a few minutes and once it is approved it will be added along with the other LF AI & Data Foundation projects. Overtime if you want to add additional repos or for general questions you can always submit a ticket here. Please let us know when this has requested.

**Comment by jzcardoso** [comment]
@ibrahimhaddad Is there an update on the project website and CII badging? Hoping to get the pending items on this onboarding closed out due to the ongoing backlog.

**Comment by ibrahimhaddad** [comment]
I emailed Mathieu Galtier and cc-ed you. He's on vacation until Aug 18th.

**Comment by jzcardoso** [comment]
@camillemarini Please assist in completing this item ASAP as the ticket on our end is still pending: LFX Insights -- As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the the substra workspace? Please confirm when complete so that our product team can add the project.

**Comment by jzcardoso** [comment]
Requested project update from Eric Boniface.
