### ISSUE TITLE
Onboarding Tracker for Kompute

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#22]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Sandbox
**--Company Sponsor (Full Legal Name):** The Institute for Ethical AI & Machine Learning
**--Jurisdiction of Incorporation:** UK
**--Project Sponsor Contact:** Alejandro Saucedo <a@ethical.institute>
**--Technical Contact:**   Alejandro Saucedo <a@ethical.institute>
**--Legal Contact:** Alejandro Saucedo
**--TAC Sponsor:** Ibrahim Haddad
**--TAC Approval Date:** 05/06/2021
**--Project in SFDC:** [Link](https://linuxfoundation.lightning.force.com/lightning/r/Project__c/a092M00001KWrRoQAL/view)
**--Project License:** Apache 2.0
**--Project Presentation:** [deck](https://wiki.lfaidata.foundation/download/attachments/7733341/May%206%2C%202021_LF%20AI%20TAC%20Deck.pdf)
**--Project Proposal per LF AI & Data:** https://github.com/lfai/proposing-projects/blob/master/proposals/Kompute.adoc
**--Project Artwork:**  https://github.com/KomputeProject/artwork

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected 
- [x] (Tech/ED) Determine known components/dependencies not under compatible license 

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Verify [CII Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status 

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation 
- [x] (Tech/ED) Domain name confirmation // Kompute.cc - transferred
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) kompute.cc**

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei) 
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/) 
- [x] (PM) Set up other misc collaboration agreed upon during proposal/acceptance, if any --N/A
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project -- Pending response to onboarding email -- None requested
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LFX Insights dashboard, then create ticket via Jira Service Desk for request  --Jira: https://jira.linuxfoundation.org/browse/SUPPORT-6098
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) - Added on LFX Portal under 'Secure My Project' section (top right) **--Requested project lead to request, see comments below - Pending verification**
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck 
- [x] (PM) Update "[LF AI & Data Overview] (https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck 
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo] (https://github.com/lfai/presentations)

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) --Jira: https://jira.linuxfoundation.org/browse/LP-7698
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (Ref LP-6711) --Jira: https://jira.linuxfoundation.org/browse/LP-7699
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis -- Will be included in Q3 announcement, targeted for Oct --Added to internal comms planning
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) --Added to internal comms plannings
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) --None at time of onboarding

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ + Planned through Software Freedom Law Center for Graduate level projects, add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) --Added to tracking --Jira: https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-678
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
@axsaucedo Please see details below on the following action item for you: 

LFX Security -- We would like to include your project in the LFX Security tool. As the project lead, please take a few minutes to submit the request for your project by visiting the LFX Security page, click on "Secure My Project" on the top right, and follow the prompts. The process takes only a few minutes and once it is approved it will be added along with the other LF AI & Data Foundation projects. Overtime if you want to add additional repos or for general questions you can always submit a ticket here. Please let us know when this has requested.

**Comment by axsaucedo** [comment]
Thank you for the heads up @jzcardoso - I can confirm that I have now submitted the request for this. Please let me know if there's any further steps required for this or other requirements.

**Comment by jzcardoso** [comment]
@axsaucedo Thank you for taking care of that and for letting me know. I'll check LFX Security and will confirm it gets added and will cross this item off the list. Everything else looks to be in motion so we are good shape at this point.

**Comment by jzcardoso** [comment]
@axsaucedo Our LFX Security is undergoing a backend change which will be fully launched with scans resuming mid September. Since this ticket was in the middle of that migration, the instructions are a little different which lead our product team to provide you the permissions to complete the set up. When you have a moment, can you please follow the instructions below? 

_I was able to assign him permissions on his EthicalML username. He can log into the direct link to Kompute in the PCC at [2]https://projectadmin.lfx.linuxfoundation.org/project/a092M00001KX0buQAD He'll be able to select "Security" under "Tools" and follow the steps to install the bot on the org.

**Comment by axsaucedo** [comment]
Thank you @jzcardoso - I have tried to activate it but it seems whilst they activated the EthicalML account, they didn't activate it for the account KomputeProject, which is the new organisation that hosts the kompute project (https://github.com/KomputeProject/kompute). Would they be able to give access to the KomputeProject account? Once they do that I will be able to proceed and activate with the instructions provided.

**Comment by jzcardoso** [comment]
@axsaucedo Let me circle back with our team on this. Sorry for the trouble.

**Comment by axsaucedo** [comment]
No worries, thank you @jzcardoso

**Comment by jzcardoso** [comment]
@axsaucedo I think there is some confusion on the access for this as the access needs to be given to an LF ID per the note below:

"I didn't find an LF account called KomputeProject. If he's referring to the GitHub user called KomputeProject, then he'd need to create a corresponding LF account with that username before I can give it access in the PCC."

**Comment by axsaucedo** [comment]
Thank you for the confirmation @jzcardoso , I don't think I fully know what is being referred as a "LF account", where would that account be expected to be created? I would be happy to be intro'd via email if it helps make the conversations more efficient. Happy to create any releevant LF ID, but I don't think I'm clear where this would be created, as I also never created any LF ID with the name of "EthicalML"

**Comment by axsaucedo** [comment]
@jzcardoso apologies, I think the one confused here was me - I think this may be correctly configured now, I have now been able to log in with that account and verify that both repos have the bot installed correctly. I have attached an image below - is this the expected results?

![image](https://user-images.githubusercontent.com/1447507/130514512-51c7a4c0-3eeb-4af7-b8aa-49f14c69175b.png)

**Comment by jzcardoso** [comment]
@axsaucedo No worries, this is a slightly new process so the instructions can definitely use some updating, thank you for your patience. Yes, looks like you are all set now. The new service will start doing scans again in mid Sept.
