### ISSUE TITLE
Milvus Graduation Checklist

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#26]
The following tasks are required to complete for projects which have moved from the Incubation level to Graduate level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:** Milvus
**--Proposal URL:**https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=7733341&preview=/7733341/43286814/June%203%2C%202021_LF%20AI%20TAC%20Deck.pdf
**--Graduation Date:**06/03/21 TAC Approval, 06/08/21 GB Approval
**--Technical Lead Contact:**Jun Gu, jun.gu@zilliz.com

**ITEMS TO COMPLETE**
- [x] Include TAC Graduation item for voting in next Governing Board meeting
- [x] Update project flag to Graduated on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=graduated) (will auto update Graduated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Graduate level + Update 'Learn More' section with Graduation date
- [x] Update [TAC wiki](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=7733341#TechnicalAdvisoryCouncil(TAC)-MemberRepresentatives) with Graduated project + project lead info for TAC voting representation
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Graduate flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Graduate flag, if wiki space is used
- [x] Add project lead to [tac-private mailing list](https://lists.lfaidata.foundation/g/tac-private/members) for voting representatives
- [x] Add project lead to [outreach-committee mailing list](https://lists.lfaidata.foundation/g/outreach-committee/members) for observer role inclusion
- [x] Send meeting invite to project lead to participate in Outreach Committee meetings as an Observer role (optional) 
- [x] Send [welcome/info note](https://docs.google.com/document/d/138IK-pNccyFO11DzVN7tRkUaplzoNIgFJfPvnCzkREo/edit) to project lead
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination **--Jira image completed: https://jira.linuxfoundation.org/browse/LP-7541** **--Announcement draft pending project approval**
- [x] Create CS ticket to update LF AI & Data Timeline with new technical project under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub] 
(https://github.com/lfai/presentations/tree/master/Timeline) **--Jira pending: https://jira.linuxfoundation.org/browse/LP-7540**
- [x] Update [LF AI & Data Getting Involved Deck](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit?ts=5c5b8268#slide=id.p1) - Project slide + Landscape slide
- [x] Update [LF AI & Data Overview Deck ](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit#slide=id.p2)- Timeline slide **--Pending Landscape update and Timeline image update**
- [x] Update LF AI & Data Getting Involved + Overview Decks on [LF AI & Data GitHub](https://github.com/lfai/presentations) **--Pending updates to decks**

**Comment by jzcardoso** [comment]
@ibrahimhaddad Please update the Landscape with a Graduate flag when you have a moment.

I have started the other tasks on the checklist.
