### ISSUE TITLE
Onboarding Tracker for TonY 

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#27]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation
**--Company Sponsor (Full Legal Name):** LinkedIn
**--Project Sponsor Contact:** Ibrahim Haddad
**--Technical Contact:** Keqiu Hu <khu@linkedin.com>
**--Legal Contact:** Renee Brown
**--TAC Sponsor:** Nancy Rausch (SAS)
**--TAC Approval Date:** 07/15/2021
**--Project in SFDC:**
**--Project License:** BSD 2-CLAUSE LICENSE
**--Project Presentation:** [Presentation to the TAC](https://docs.google.com/presentation/d/1XwqtINb0aYCSbs3X4UGKBde5U_526bctiKySQ8SDcl0/edit?usp=sharing)
**--Project Proposal per LF AI & Data:** [Proposal on GH](https://github.com/lfai/proposing-projects/blob/master/proposals/tony.adoc)
**--Project Artwork:** https://github.com/lfai/artwork/tree/main/projects/tony

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // **ongoing**
- [x] (Tech/ED) Determine known components/dependencies not under compatible license **ongoing**

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Verify [CII Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // Ongoing with Creative
- [x] (Tech/ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // Bought tony-project.ai
- [x] (Tech/ED) Project website confirmation // If no website exists (as noted above), request a new website creation via Creative Services Jira ticket (Include request for project lead to be added as authorized user for Word Press for future website updates, requires -name/email of authorized user) **--Update Getting Involved Guide + LF AI & Data Project Page with website URL once published** --Jira: https://jira.linuxfoundation.org/browse/LP-7967
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668)  

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/) 
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration agreed upon during proposal/acceptance, if any --N/A
- [x] (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project - -None requested
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project  --None requested 
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LFX Insights dashboard, then create ticket via Jira Service Desk for request -- Jira completed: https://jira.linuxfoundation.org/browse/SUPPORT-6084
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) - Added on LFX Portal under 'Secure My Project' section (top right) --Jira: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-6550
- [x] (PM) Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck 
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) --N/A

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) -- Jira: https://jira.linuxfoundation.org/browse/LP-7693
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (Ref LP-6711) --Jira: https://jira.linuxfoundation.org/browse/LP-7694
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) --Added to comms planning
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) --Draft approved, published 8/24
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) **--Will need to do for Slack per proposal --Sent project instructions for transfer on 08/27/21, Erin will work with project lead to complete

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434) --Added to tracking
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ + Planned through Software Freedom Law Center for Graduate level projects, add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) -- Legal (trademark/contribution agreement + website needed for filing) for Jira ticket submission --Jira: https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-692
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876) --Added to tracking

**Comment by ibrahimhaddad** [comment]
This is incubation project. Not sure where you see Graduate. I think I copied the text from the Incubation template.

**Comment by jzcardoso** [comment]
@oliverhu A couple of items for you regarding this onboarding checklist:

- LFX Insights -- As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the TonY workspace? Please confirm when complete so that our product team can add the project.

- LFX Security -- We would like to include your project in the LFX Security tool. As the project lead, please take a few minutes to submit the request for your project by visiting the LFX Security page, click on "Secure My Project" on the top right, and follow the prompts. The process takes only a few minutes and once it is approved it will be added along with the other LF AI & Data Foundation projects. Overtime if you want to add additional repos or for general questions you can always submit a ticket here. Please let us know when this has requested.

**Comment by oliverhu** [comment]
@jzcardoso  invited dev-analytics-bot@linuxfoundation.org!

**Comment by oliverhu** [comment]
@jzcardoso  for LFX security, do we need to do it now? We are still in the process to transfer the repo to a new GitHub org.

**Comment by jzcardoso** [comment]
@oliverhu Thanks for confirming the invite was sent. We can hold on the LFX Security if you would like. I will add a note to the ticket.

**Comment by jzcardoso** [comment]
@ibrahimhaddad Can you please confirm once the following two items are completed: DCO enablement and GH code migration

@oliverhu Once the GH code is migrated, please move forward with the LFX Security request and confirm when that's requested - We can then track that item to completion

We will work on the website build and social account transfer post announcement.

**Comment by oliverhu** [comment]
@jzcardoso I've requested LFX security review.

**Comment by jzcardoso** [comment]
@oliverhu Thanks for completing the request for LFX Security. We will track it to complete on this onboarding tracker.

**Comment by jzcardoso** [comment]
@oliverhu Unfortunately there was an issue with the slack invite expiring. Can you please resend that and I will let the product team know once you confirm it is sent so they can accept it quickly this time? " As part of the LFX Insights tracking that is set up, for slack, can you please send an invite at 'dev-analytics-bot@linuxfoundation.org' to join the the tony workspace? Please confirm when complete so that our product team can add the project. "

**Comment by oliverhu** [comment]
@jzcardoso  'dev-analytics-bot@linuxfoundation.org' is already in the tony workspace.

**Comment by jzcardoso** [comment]
Thanks for the update @oliverhu, I will have our product team recheck.

**Comment by jzcardoso** [comment]
@oliverhu Our product team is stating the following: "Doesn't look like this email is in the workspace already. This is the workspace I am trying to join [4]https://li-tony.slack.com/_" 

Can you confirm that this is the workspace you added to?

**Comment by oliverhu** [comment]
Yes...I can see the account.

**Comment by jzcardoso** [comment]
@oliverhu how very strange. would it be possible for you to remove them and re-add them? perhaps it will trigger the correct view? very sorry for the inconvenience on this item.

**Comment by oliverhu** [comment]
Just re-invited `dev-analytics-bot@linuxfoundation.org`

**Comment by jzcardoso** [comment]
Hello @oliverhu Our product team is now ready to onboard Tony into LFX Security. Your LFX account should now have access to install and manage the Security bot on the org: https://projectadmin.lfx.linuxfoundation.org/project/a092M00001Lk7lNQAR/tools/security/overview 

If you can complete this step and confirm when done that would be great.

**Comment by oliverhu** [comment]
Done!

**Comment by jzcardoso** [comment]
@oliverhu Great, thank you for your help with that item. You should expect to hear back on the website build shortly as well which is the last item on the onboarding checklist.
