### ISSUE TITLE
Onboarding Tracker for Kedro

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#30]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation 
**--Company Sponsor (Full Legal Name):** QuantumBlack Labs (McKinsey & Company) 
**--Jurisdiction of Incorporation:**
**--Address:**
**--Project Sponsor Contact:**  [Yetunde Dada](Yetunde_Dada@mckinsey.com)
**--Technical Contact:** [Yetunde Dada](Yetunde_Dada@mckinsey.com)
**--Legal Contact:**
**--TAC Sponsor:** Ibrahim Haddad 
**--TAC Approval Date:** 08/26/2021
**--Project in SFDC:** https://linuxfoundation.lightning.force.com/lightning/r/Project__c/a092M00001Lk9rsQAB/view
**--Project License:** Apache 2.0
**--Project Presentation:** [Deck](https://wiki.lfaidata.foundation/download/attachments/7733341/August%2026%2C%202021_LF%20AI%20TAC%20Deck.pdf?version=1&modificationDate=1630089002110&api=v2)
**--Project Proposal per LF AI & Data:** https://github.com/lfai/proposing-projects/blob/master/proposals/kedro.adoc
**--Project Artwork:** [URL](https://drive.google.com/file/d/1LveDRAI60B5w3QOTWQ46h8Hm4rskFKFm/view?usp=sharing)

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // **ongoing**
- [x] (Tech/ED) Determine known components/dependencies not under compatible license // **ongoing**

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project // **ongoing**
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project  // **ongoing**
- [x] (Tech/ED) Verify [CII Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status --moved task to Trello board, closed for onboarding purposes // Passing --> https://bestpractices.coreinfrastructure.org/en/projects/6711

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation 
- [x] (Tech/ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // If no domain is registered, then one is to be purchased // If one exists, it must be transferred using https://jira.linuxfoundation.org/servicedesk/customer/kb/view/28485232 // Reference: https://confluence.linuxfoundation.org/display/LID/Domain+Registration+and+Transfers  --https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-23993
- [x] (Tech/ED) Project website confirmation // Waiting to decide on domain and then receive text for website (low priority) https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-23993
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) --marked TBD in LF internal tracking document

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)  
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration agreed upon during proposal/acceptance, if any -- N/A
- [x] (PM) Set up project Zoom account (Requires new LF AI & Data email alias for new account set up) - Upon request only per onboarding email info provided to project --None noted in proposal
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project -- None noted in proposal
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LFX Insights dashboard, then create ticket via Jira Service Desk for request -- Insights v.2 onboarded
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) - Project lead will need to make request, request on LFX Portal under 'Secure My Project' section (top right) 
- [x] (PM) Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck **--Added, need to verify/update final GitHub link and website link** --Erin updated deck with https://github.com/kedro-org link, updated website link to https://kedro.readthedocs.io/en/stable/index.html 
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) --None requested in proposal

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required (Ref LP- 6341) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) --Jira: https://jira.linuxfoundation.org/browse/LP-7812
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (Ref LP-6711) -- Jira: https://jira.linuxfoundation.org/browse/LP-7813 **--Published but need to update final GitHub link and website link** --Erin updated with GitHub https://github.com/kedro-org and website https://kedro.readthedocs.io/en/stable/index.html 
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) **--Drafted, shared with project lead on 09/08/21, will be published by Erin once finalized -- Publishing target date TBD based on legal/tech/marketing task requirement completion**
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) -- None listed in proposal, Slack set up after proposal - pending transfer on it

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects **--Pending legal docs + website for Jira ticket** --marked as resolved on 09/27/2022, tracked in LF AI & Data Trello Board for legal follow up w/ Jeff Shapiro
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
Invited Yetunde Dada to LF AI & Data GH to join Kedro onboarding tracker.

**Comment by jzcardoso** [comment]
@ErinThacker Please note that there were no social accounts listed in the Kedro proposal but they are creating a Twitter account @kedro_org which will need to be transferred. Post announcement is fine.

**Comment by jzcardoso** [comment]
@ibrahimhaddad Is there an update on the following:
1. License scanning completion?
2. OpenSSF badge? I did a search but couldn't find the project.
3. Did they decide whether they are creating a website?

**Comment by ErinThacker** [comment]
@jzcardoso - I followed up again on the legal support ticket for an update on export control filings. I'm working on finding out when Insights projects onboarding will resume.

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you give me an update on these items: Licensing (FOSSology scan), Contribution (CII Badge status), Project Assets (domain name & website confirmation, project website tracking)

**Comment by ErinThacker** [comment]
Insights and Slack social media transfer pending

**Comment by ErinThacker** [comment]
Final pending item was related to social media transfer, project has been unresponsive on transferring admin credentials. Numerous follow-ups completed, will close out issue and note single item pending in internal Trello board filed under backlog. Impact to project will be no back-up or continuity support from LF staff for account.
