### ISSUE TITLE
Onboarding Tracker for OpenBytes

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#31]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Sandbox
**--Company Sponsor (Full Legal Name):** Graviti 
**--Project Sponsor Contact:**
**--Technical Contact:** Edward Cui - edward.cui@graviti.com
**--Legal Contact:** Katerina Zhou - Katerina@graviti.com
**--TAC Sponsor:** 
**--TAC/GB Approval Date:** 10/21/2021
**--Project in SFDC:**
**--Project License:** Creative Commons Attribution 4.0 International and Apache 2.0
**--Project Presentation:** [Deck](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=7733341&preview=/7733341/51053320/October%2021%2C%202021_LF%20AI%20TAC%20Deck.pdf#TechnicalAdvisoryCouncil(TAC)-MeetingAgendas)
**--Project Proposal per LF AI & Data:** [Proposal](https://github.com/lfai/proposing-projects/blob/master/proposals/OpenBytes.adoc) 
**--Project Artwork:** **In progress with Alex**

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected // not applicable
- [x] (Tech/ED) Determine known components/dependencies not under compatible license // not applicable

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0)) // not applicable - new project 
- [x] (Tech/ED) Verify [CII Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status // **ongoing** --follow up with item on Trello board, item closed for onboarding (https://bestpractices.coreinfrastructure.org/en/projects?q=OpenBytes)

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation
- [x] (Tech/ED) Domain name confirmation // openbytes.io ongoing via IT-23343
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Set up other misc collaboration agreed upon during proposal/acceptance, if any -- n/a
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project  -- none requested
- [x] (PM) Create new tab for project in [LF AI & Data Tracking](https://docs.google.com/spreadsheets/d/1UFZuJDJg2xApaK6QRNREnqxsPJfxtmKExDPM1tyE2OQ/edit#gid=0) to have project added to LFX Insights dashboard, then create ticket via Jira Service Desk for request -- GitHub repo, Slack URL, groups.io mailing lists -- waiting on access to spreadsheet, but will put ticket in to LFX Insights (https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-7458) 
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) - Project lead will need to make request, request on LFX Portal under 'Secure My Project' section (top right) **--Product relaunch in motion, updated process for project lead to submit request to be updated** --(https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-7789) --provided LF ID OpenBytes to Support ticket on 01.19.2022
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required (https://jira.linuxfoundation.org/browse/LP-8035) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (https://jira.linuxfoundation.org/browse/LP-8037) -- in progress
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker] (https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis  --added to comms tracker, tentative Dec. publication date with Group Announcement
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) -- December Q4 Announcement
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) --LinkedIn: https://www.linkedin.com/company/openbytes/, Slack: https://openbytes.slack.com/ --finish Slack 01.19.2022

**LEGAL FOLLOW UP**
- [x] (PM) Confirm ongoing license scanning is set up through Steve W. - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through Steve W. for all projects via ticket at https://www.linuxfoundation.org/export/ (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ- rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects (https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-886) --resubmitted ticket to add project to our export control filings page, followed up on 1/12/2022 --see note from Mike Dolan dated 01/24/2022, followed up on 02/15/2022 --marked as resolved on 09/27/2022, tracked in LF AI & Data Trello Board for legal follow up w/ Jeff Shapiro
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
@ibrahimhaddad Can you please share the ticket for the domain name transfer for this project? 

Also, is the CII badging URL link available for tracking? Initial search does not come up with anything in progress.

**Comment by jzcardoso** [comment]
@ErinThacker Please go ahead and submit the LFX Security ticket per my Slack message and please work to close out the landing page and social transfers.

**Comment by ErinThacker** [comment]
@edward.cui@graviti.com - in order to onboard the project to LFX Security, you will need to install a bot as administrator of the GitHub repo. To do this, we need your LF ID. Can you share that with us? If you don't have an LF ID, you can register for one here: https://identity.linuxfoundation.org/

Thanks and let me know if you have any questions.

**Comment by jzcardoso** [comment]
@ErinThacker Can you please follow up on the open items in this issue?

**Comment by taylorlaw2013** [comment]
@ErinThacker  We just register the LF ID, which is: OpenBytes 
Thanks!

> @[edward.cui@graviti.com](mailto:edward.cui@graviti.com) - in order to onboard the project to LFX Security, you will need to install a bot as administrator of the GitHub repo. To do this, we need your LF ID. Can you share that with us? If you don't have an LF ID, you can register for one here: https://identity.linuxfoundation.org/

**Comment by jzcardoso** [comment]
@taylorlaw2013 - One of the requirements for the project is to have an OpenSSF Best Practices Badge (Silver) achieved. Can you please provide the link for OpenBytes and ensure that the requirements are met? Thanks!

**Comment by ErinThacker** [comment]
@jzcardoso - I followed up again on the legal support ticket for an update on export control filings. I'm working on finding out when Insights projects onboarding will resume.

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you provide an update on the CII Badge?
