### ISSUE TITLE
Graduation Tracker for ART

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#34]
The following tasks are required to complete for projects which have moved from the Incubation level to Graduate level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion.

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

PROJECT INFORMATION

--Project Name: ART (Adversarial Robustness Toolkit)
--Proposal URL: [URL](https://docs.google.com/presentation/d/1q6K63VRHSRO8IwSLO8WfPdD4QDbH-kcs/edit?usp=sharing&ouid=110717194519976184479&rtpof=true&sd=true)
--Graduation Date: TAC vote 1/13/2022 - GB vote scheduled for 02/08/2022
--Technical Lead Contact: [Beat Buesser](mailto:beat.buesser@ie.ibm.com) 

ITEMS TO COMPLETE

- [x]  Include TAC Graduation item for voting in next Governing Board meeting // Scheduled for 02/15/2022
- [ ]  Update project flag to Graduated on LF AI & Data Landscape (will auto update Graduated Projects on LF AI & Data website) --Ibrahim will update
- [ ]  Update project landing page on LF AI & Data website to reflect Graduate level + Update 'Learn More' section with Graduation date
- [ ]  Update TAC wiki with Graduated project + project lead info for TAC voting representation
- [ ]  Update LF AI & Data wiki project list with Graduate flag
- [ ]  Update project space homepage on LF AI & Data wiki with Graduate flag, if wiki space is used
- [ ]  Add project lead to tac-private mailing list for voting representatives
- [ ]  Send welcome/info note to project lead
- [x]  Add graduation announcement to LF AI & Data PR/Comms Tracking to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination -- (https://jira.linuxfoundation.org/browse/LP-8175)
- [x]  Create CS ticket to update LF AI & Data Timeline with new technical project under month accepted + Save in Google Drive + Update on GitHub -- (https://jira.linuxfoundation.org/browse/LP-8174)
- [ ]  Update LF AI & Data Getting Involved Deck - Project slide + Landscape slide
- [ ]  Update LF AI & Data Overview Deck - Projects slide + Structure & Governance slide
- [ ]  Update LF AI & Data Getting Involved & Overview Decks on LF AI & Data GitHub

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you please update the project flag to Graduated on the landscape? Thank you!

**Comment by jzcardoso** [comment]
Hold off on this until Feb 8th after the Governing Board approves it. I
forgot to remind you of that Erin.

Thank you,
Jacqueline

Jacqueline Z Cardoso
Senior Program Manager
The Linux Foundation
+1 (415) 676-1127 (m)
***@***.***
Hours: Mon-Thurs, 6am-4pm PT

*My working day may not be your working day. Please don't feel obliged to
reply to this e-mail outside of your normal working hours.*
