### ISSUE TITLE
[Template Project Graduation Checklist (Sandbox>Incubation)] #24

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#36]
**COPY (click edit then copy the content to include formatting in paste) ISSUE FOR EACH SANDBOX LEVEL PROJECT WHICH MOVES TO INCUBATION LEVEL + ASSIGN TO LF AI STAFF + PROJECT LEAD**

The following tasks are required to complete for projects which have moved from the Sandbox level to Incubation level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:**
**--Proposal URL:**
**--Graduation Date:**
**--Technical Lead Contact:**

**ITEMS TO COMPLETE**
- [ ] Update project flag to Incubation on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=incubating) (will auto update Incubated Projects on LF AI & Data website)
- [ ] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Incubation level + Update 'Learn More' section with Graduation date
- [ ] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Incubation flag
- [ ] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Incubation flag, if wiki space is used
- [ ] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [ ] Create CS ticket to update LF AI & Data Timeline with project graduation under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline)
- [ ] Update [LF AI & Data Getting Involved Deck](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit?ts=5c5b8268#slide=id.p1) - Project slide + Landscape slide
- [ ] Update [LF AI & Data Overview Deck](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit#slide=id.gf988cdf65c_2_0) - Projects slide + Structure & Governance slide
- [ ] Update LF AI & Data Getting Involved & Overview Decks on [LF AI & Data GitHub](https://github.com/lfai/presentations)
