### ISSUE TITLE
Kompute Project Graduation Checklist (Sandbox >> Incubation)

### ISSUE THREAD

**Issue by jzcardoso** [lfai/foundation#37]
The following tasks are required to complete for projects which have moved from the Sandbox level to Incubation level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:** Kompute 
**--Proposal URL:**  [URL to graduation proposal](https://docs.google.com/presentation/d/13YgYUN6NkXzNmf145_vlagfEf5CYlrNp/edit?usp=sharing&ouid=110717194519976184479&rtpof=true&sd=true)
**--Graduation Date:** February 10, 2022
**--Technical Lead Contact:** Alejandro Saucedo

**ITEMS TO COMPLETE**
- [x] Update project flag to Incubation on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=incubating) (will auto update Incubated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Incubation level + Update 'Learn More' section with Graduation date
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Incubation flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Incubation flag, if wiki space is used
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [x] Create CS ticket to update LF AI & Data Timeline with project graduation under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline) --ticket created https://app.asana.com/0/1201265796032457/1201886628428405/f 
- [x] Update [LF AI & Data Getting Involved Deck](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit?ts=5c5b8268#slide=id.p1) - Project slide + Landscape slide
- [x] Update [LF AI & Data Overview Deck](https://docs.google.com/presentation/d/1SPUXnS89U8M7gIr_FM3_dzBMaabppHonLi2Kt-vIXf8/edit#slide=id.gf988cdf65c_2_0) - Projects slide + Structure & Governance slide
- [x] Update LF AI & Data Getting Involved & Overview Decks on [LF AI & Data GitHub](https://github.com/lfai/presentations)

**Comment by jzcardoso** [comment]
@axsaucedo As mentioned last week, we are sharing this checklist for your reference. These actions are all going to be completed by our team. You can expect to work with Erin on the announcement plans otherwise we will be all set. Of course, if you have any questions, please do let us know!

**Comment by axsaucedo** [comment]
Thank you for the heads up @jzcardoso - I have started a blog post draft for the announcement which I will share with Erin shortly, I will make sure to coordinate with her. Please let me know if you need any more details to complete any of the required tasks. Thank you as always for the great efforts!
