### ISSUE TITLE
Onboarding Tracker for 1chipML

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#40]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Sandbox
**--Company Sponsor (Full Legal Name):** Ericsson 
**--Project Sponsor Contact:** Rani Yadav-Ranjan / rani.yadav-ranjan@ericsson.com
**--Technical Contact:** Jean Michel Sellier / jean.michel.sellier@ericsson.com 
**--TAC Sponsor:** Rani Yadav-Ranjan / rani.yadav-ranjan@ericsson.com
**--TAC/GB Approval Date:** 04/07/2022
**--Project in SFDC:**
**--Project License:** Apache 2.0 
**--Project Presentation:** [URL](https://docs.google.com/presentation/d/17lvVcSny3Tc2-U1qWH62PmkM_85LvJTl/edit?usp=sharing&ouid=110717194519976184479&rtpof=true&sd=true) to Google Slides 
**--Project Proposal per LF AI & Data:** [URL](https://github.com/lfai/proposing-projects/blob/master/proposals/1chipML.md) to proposal on GH
**--Project Artwork:** https://github.com/1chipML/artwork 

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project 
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project [not required]
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) link and passing status:https://bestpractices.coreinfrastructure.org/en/projects/5704

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // If logos exist post to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // Reserved 1chipml.org for future use
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei) **--Pending final charter**
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any --N/A
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project - None requested at time of onboarding
- [x] (PM) Request project to be added to [LFX Insights ](https://insights.lfx.linuxfoundation.org/) via Jira Service Desk for request **--Pending Jira: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-9600, requests on hold until June for v2 of LFX Insights** --marked as resolved on 09/27/2022, tracked in LF AI & Data Trello Board for Insights v.2 release on 09/30/2022.
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) via Ibrahim Haddad (Admin on GH repo for project) OR via Jira Service Desk for request (will need to first confirm LF ID for project lead for access to be granted for bot installation on GitHub repo) **--Requested via Ibrahim**
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1FGFbHmopmYUrMeH2pPeYTBaECM6MqV9qfaLcV85xu24/edit?usp=sharing)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) --Ticket: https://app.asana.com/0/1201265796032457/1202119631285769
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required (Ref LP-6711) --Ticket: https://app.asana.com/0/1201187889631310/1202119643716344
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis -- Added to tracker
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable - N/A
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) --To be included in Sandbox blog to be published in July
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) -- None at time of proposal

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through for all projects via ticket at https://www.linuxfoundation.org/export/ (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects --**Pending Jira: https://legaljira.linuxfoundation.org/servicedesk/customer/portal/1/LR-1046** --marked as resolved on 09/27/2022, tracked in LF AI & Data Trello Board for legal follow up w/ Jeff Shapiro
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by jzcardoso** [comment]
@ibrahimhaddad do you have access for this project to add them to LFX Security?

**Comment by ErinThacker** [comment]
@ibrahimhaddad - can you give me an update on these items: Licensing (FOSSology scan & known components/dependencies)

**Comment by ibrahimhaddad** [comment]
All onboarding tasks have been completed. @jmsellier @jzcardoso @ErinThacker 
Thanks all.
