### ISSUE TITLE
Onboarding Tracker for CLAIMED

### ISSUE THREAD

**Issue by ibrahimhaddad** [lfai/foundation#48]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Sandbox
**--Company Sponsor (Full Legal Name):** IBM
**--Project Sponsor Contact:** [Romeo Kienzler](mailto:romeo.kienzler@ch.ibm.com)
**--Technical Contact:** Romeo Kienzler
**--Legal Contact:**
**--TAC Sponsor:** Ibrahim Haddad
**--TAC/GB Approval Date:** 11/17/2022
**--Project in SFDC:**
**--Project License:** Apache 2.0
**--Project Presentation:** [URL](https://drive.google.com/file/d/1sj8Xtx8eOc1Zr5SO1UQO4NS-Q4FGG4ju/view?usp=share_link) to presentation
**--Project Proposal per LF AI & Data:** [URL](https://github.com/lfai/proposing-projects/blob/master/proposals/claimed.adoc) to proposal 
**--Project Artwork:** logos available from https://github.com/lfai/artwork/tree/main/projects/claimed

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [ ] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en): https://bestpractices.coreinfrastructure.org/en/projects/6718

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // If logos exist post to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // We bought **claimed-framework.org**
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei) - pending
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project 
- [x] (PM) Request project to be added to [LFX Insights ](https://insights.lfx.linuxfoundation.org/) via Jira Service Desk for request
- [x] (PM) Request project to be added to [LFX Security](https://security.lfx.linuxfoundation.org/#/a0941000012Y73ZAAS/foundation-details) via Ibrahim Haddad (Admin on GH repo for project) OR via Jira Service Desk for request (will need to first confirm LF ID for project lead for access to be granted for bot installation on GitHub repo)
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Getting Involved Guide](https://docs.google.com/presentation/d/1VLji1GuFsj6Plvlivborohpg7RAxBgeRMbRuhuX7Qm4/edit#slide=id.p1)" deck
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1FGFbHmopmYUrMeH2pPeYTBaECM6MqV9qfaLcV85xu24/edit?usp=sharing)" deck
- [x] (PM) Upload "LF AI Getting Involved Guide" and "LF AI Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations) 
- [x] (PM) Verify project is added to [Project Website Access](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) tracking + verify all information is added per details under "Project Assets" section in this issue

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - https://app.asana.com/0/1201265796032457/1203511775324675 - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required ([Reference](https://app.asana.com/0/1201187889631310/1202119643716344
)) --https://app.asana.com/0/1201187889631310/1203558875791580
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)
- [x] (Mktg) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing) --none identified in proposal

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through legal - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm export control filings are done through legal via ticket at https://www.linuxfoundation.org/export/ (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by romeokienzler** [comment]
TASKS for IBM/CLAIMED team 
> 
> 1) Please fill out the Project Intake Form to provide basic needed
> info for our project formation team 

DONE

> 
> 2) Please submit a GH PR proposal similar to other projects in this
> repo. 

DONE


> 
> 3) Review and be ready to sign the project contribution agreement

DONE, we are ready

> 
> 4) Review and provide feedback on the standard Project Charter -
> template attached 
> 
> Please send in any questions along with information about the
> company, address, and signatory name/title/email. On the above items,
> please connect with @Scott Nicholas who is our VP of
> Project Formation and Senior Counsel. 
> 

DONE, looks good to us

> 
> 5)   a. Create a new GH Org for the project such
> as https://github.com/claimed-ai 
>       b. Transfer the CLAIMED repo from the IBM GH org to the new
> org 
>       c. Add @IbrahimHaddad and @thelinuxfoundation as owners of the
> new GH org 

DONE
https://github.com/claimed-framework
@IbrahimHaddad accepted the invitation @thelinuxfoundation not


> 
> 6) Please activate the GitHub DCO app on all
> repos.- https://github.com/apps/dco

DONE

>  
> 7) Domain -- do you have a domain name for the project? If yes, we
> need to transfer it to the LF. Please share the domain names and I
> will issue a ticket for the transfer. Otherwise, please let me know
> what domain name should we reserve for the project. We will use that
> domain to host a website for the project or to simply lock the domain
> and we can do a FW to the GH org

I'd go for claimed-framework.org, what you think?

> 
> 8) Does the project have a logo? If yes, please send us a
> high-resolution version project's logo. 
> Otherwise, we will introduce you to our Creative team that will help
> design a logo for the project. 

Yes, here is the logo
https://raw.githubusercontent.com/claimed-framework/component-library/master/images/claimed_logo.png

> 
> 9) Let me know what sub-category on https://l.lfai.foundation/ the
> project fits under best. I will then add the project to the landscape
> as a Sandbox project. 
> 

DONE

> 10) Does the project have any social media accounts? LI? TW? FB? etc.
> If yes, please coordinate with @Erin Thacker  on facilitating access
> to these accounts.

Space with attached rooms on Matrix.org => claimed:matrix.org
No other social media accounts yet

Thanks so much!

**Comment by romeokienzler** [comment]
@ibrahimhaddad also for this [list](https://github.com/lfai/tac/blob/main/github-recommendations.md) we are happy to announce that we're already covering everything but 15 and 16

**Comment by romeokienzler** [comment]
- [ ] Use the [REPOLINTER](https://github.com/todogroup/repolinter) tool created by the TODO Group to identify common issues in GitHub repos.

- [ ] Secure your GitHub account with two-factor authentication.

    

- [ ] Ensure that every repo includes a LICENSE file.

    

- [ ] Add a README file to your repos welcoming new community members to the project and explaining why the project is useful and how to get started.

    

- [ ] Add a CONTRIBUTING file to your repos explaining to other developers and your community of users how to contribute to the project. At a high level, the file would explain what types of contributions are needed and how the process works.

    

- [ ] Add CODEOWNERS file to define individuals or teams that are responsible for code in a repository.

    

- [ ] Add a CODE_OF_CONDUCT file that sets the ground rules for participants’ behavior associated and helps to facilitate a friendly, welcoming environment. While not every project has a CODE_OF_CONDUCT file, its presence signals that this is a welcoming project to contribute to, and defines standards for how to engage with the project’s community. You are welcome to use the Linux Foundation’s Code of Conduct if project specific CoC does not exist.

    

- [ ] Provide documentation on the release methodology, cadence, criteria, etc.

    

- [ ] Document your project governance and make it available on the project’s repo.

    

- [ ] Add a SUPPORT file to let users and developers know about ways to get help with your project. You can either add in this file how and where security issues are handled, or put it at the top level readme for the project, or alternatively refer to security documentation.

    

- [ ] Archive inactive repos to flag to your users and other developers that you’re not maintaining them.

    

- [ ] Setup issue template and pull request templates that help you customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

    

- [ ] Achieve and maintain the [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (previousely called the Core Infrastructure Initiative Best Practices Badge) for your project.

    

- [ ] Identify who on the project will be handling security issues (could be a team) and set up a separate email account. Consider having the project become a CNA (CVE Numbering Authority).

    

- [ ] Include an SPDX short-form identifier in a comment at the top of each file in the repo, wherever reasonably possible.

    

- [ ] Depending on whether your project uses the DCO and/or CLAs:

    DCO: Include a copy of or reference to the Developer Certificate of Origin (DCO) in your CONTRIBUTING file. Set up a bot to enforce a “Signed-off-by:” tag in each commit (https://github.com/apps/dco)
    CLAs: Use the Linux Foundation’s EasyCLA tool (https://lfcla.com/) to enforce signed CLAs before contributions are accepted. In either case: Configure the Github repo settings so that administrators are not able to bypass the DCO or CLA checks.

    

- [ ] Use English as the default universal language for anything you publish on GitHub. You can support a second language but English should be the primary language of communication towards a universal audience.

**Comment by ErinThacker** [comment]
@romeokienzler - let me take a look at this for you. To be clear, are you referring to the checklist in the issue itself or the checklist you provided on Dec. 9th in the comments above?

**Comment by romeokienzler** [comment]
@ErinThacker thanks a lot, I'm referring to the issue's checklist, the one provided by myself I can handle

**Comment by ErinThacker** [comment]
@romeokienzler - it appears that the only remaining item is LFX Security, which takes installing a security bot on GitHub to finish out. You can see the instructions below: 

Log in to LFX, navigate to this link and enter your GitHub repository name:
[](https://projectadmin.lfx.linuxfoundation.org/project/a092M00001NVodlQAD/tools/security/overview )

These instructions should then pop up: 
How to install the Security Bot on GitHub App 

      1. Click on "Install Security Bot" below. You will be directed to your organization's GitHub page. 

      2. Ensure you are logged into GitHub. 

      3. Click the "Configure" button, located on the top-right corner of your organization's GitHub page. 

      4. Select the Organization that you have added in Project Control Center. 

      5. You can select all repositories or some repositories from the GitHub Organization. 

      After completing all these steps you have successfully authorized Security to view your GitHub Organization. 

Let me know if you have any questions!

**Comment by romeokienzler** [comment]
Dear @ErinThacker sorry, completely missed this, will work (and finish) this by end of next week!

**Comment by NSouthernLF** [comment]
No response from project on website, head user or assets after over a year. Closing out that item.

**Comment by NSouthernLF** [comment]
@romeokienzler is there a website on this project?

**Comment by romeokienzler** [comment]
@NSouthernLF 

Yes, claimed-framework.github.io/

**Comment by NSouthernLF** [comment]
thanks
