### ISSUE TITLE
Onboarding Tracker for OpenFL

### ISSUE THREAD

**Issue by ErinThacker** [lfai/foundation#51]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation
**--Company Sponsor (Full Legal Name):** Intel
**--Technical Contact:** Prashant Shah
**--Legal Contact:** tbd
**--TAC Sponsor:** [Ibrahim Haddad](ibrahim@linuxfoundation.org)
**--TAC Approval Date:** February 3, 2023 email vote
**--Project License:** [Apache 2.0](https://github.com/intel/openfl/blob/develop/LICENSE)
**--Project Presentation:** [URL](https://docs.google.com/presentation/d/1FX4jSFCBu9DqSydO9EkCzG2nbeoI1PP5/edit#slide=id.p1) to presentation
**--Project Proposal per LF AI & Data:** (https://github.com/lfai/proposing-projects/blob/master/proposals/OpenFL.md)
**--Project Artwork:** Logos are available from https://github.com/securefederatedai/artwork

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected 
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco 
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking] (https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) Ticket has been issued and work started:  https://bestpractices.coreinfrastructure.org/en/projects/6599

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // https://github.com/securefederatedai/artwork
- [x] (Tech/ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy) **- Pending project logos package, see above**
- [x] (Tech/ED) Domain name confirmation // **bought openfl.io**
- [x] (Tech/ED) Project website confirmation // If no website exists (as noted above), request a new website creation via Creative Services Jira ticket (Include request for project lead to be added as authorized user for Word Press for future website updates, requires -name/email of authorized user)  - **LF team created website openfl.io** 
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668)  **pending website purchase, see above**

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei) 
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/) 
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any - N/A
- [x] (PM)  Set up project to utilize LFX Meetings as applicable/upon request - requested Zoom account until LFX Meetings is online again (https://jira.linuxfoundation.org/plugins/servlet/desk/portal/3/LFIT-3711) 
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project - https://wiki.lfaidata.foundation/x/VwE2B 
- [x] (PM) Set up project in LFX Insights by adding project repo name to Source Control under Development and then adding connection in LFX Insights under LFX Tools - **pending project activation in LFX**
- [x] (PM) Set up project in LFX Security by ensuring that the security bot is installed in project GitHub repo, once that is confirmed, add connect the repo in LFX Security - **pending project activation in LFX**
- [x] (PM) Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Update "[LF AI & Data Overview](https://docs.google.com/presentation/d/1FGFbHmopmYUrMeH2pPeYTBaECM6MqV9qfaLcV85xu24/edit?usp=sharing)" deck 
- [x] (PM) Upload "LF AI & Data Overview Deck" on [LF AI & Data GH presentations repo](https://github.com/lfai/presentations)
- [x] (PM) Verify project is added to [Project Website Access](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) tracking + verify all information is added per details under "Project Assets" section in this issue - **Pending website**
- [x] (PM) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing)

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) - N/A

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services Jira ticket required ([Reference](https://app.asana.com/0/1201265796032457/1202119631285769)) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic) - https://app.asana.com/0/1201265796032457/1204099762919221 
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services Jira ticket required ([Reference](https://app.asana.com/0/1201187889631310/1202119643716344
)) - https://app.asana.com/0/1201187889631310/1204093592983501 
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists) - Published March 9

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through legal - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm Export Control Notice (ECN) filings are completed through legal via ticket at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2 (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects - Need updated request process from Jeff S.
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by ErinThacker** [comment]
@psfoley @Operepel @Prashantshahintel - take a look at this checklist, Ibrahim will send another list more specific to you all on Friday (he's traveling).

**Comment by ErinThacker** [comment]
@saritaregmi  - Adding you to the comments, I'm not sure why I'm not able to assign to you. Let me know if this works. Thanks!

**Comment by jzcardoso** [comment]
@jeffcshapiro Tagging you in this issue to ensure the request was made for a new project intake scan for OpenFL. Erin Thacker left the LF and I am not clear whether this was in your queue or not. OpenFL GitHub is: https://github.com/intel/openfl

**Comment by jzcardoso** [comment]
@ibrahimhaddad Do you have the asana ticket for the logo package you submitted? Trying to see what is pending for this onboarding and that is an item that will be needed for the website landing page and other marketing items.

**Comment by jzcardoso** [comment]
@ibrahimhaddad Can you also verify if the following was completed: 
- [ ] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [ ] (Tech/ED) Migrate code repository to new GH org

**Comment by saritaregmi** [comment]
@jzcardoso it would be helpful if the task had owner next to it? Like LEGAL FOLLOW UP (LF), XYZ (Intel + LF)

**Comment by jzcardoso** [comment]
@saritaregmi LF owns all the items and will be reaching out and coordinating accordingly with the project. This ticket and the tasks are for project reference only.

**Comment by operepel** [comment]
> @jeffcshapiro Tagging you in this issue to ensure the request was made for a new project intake scan for OpenFL. Erin Thacker left the LF and I am not clear whether this was in your queue or not. OpenFL GitHub is: https://github.com/intel/openfl

@jzcardoso OpenFL's new HitHub is https://github.com/securefederatedai/openfl

> @ibrahimhaddad Can you also verify if the following was completed:
> 
> * [ ]  (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
> * [ ]  (Tech/ED) Migrate code repository to new GH org

@jzcardoso I sent invitations to these two accounts, but they have not accepted yet.

**Comment by jeffcshapiro** [comment]
I will add it to my queue.  I have a few projects in queue before this so it might be a few days or a week or so.

**Comment by jzcardoso** [comment]
> > @jeffcshapiro Tagging you in this issue to ensure the request was made for a new project intake scan for OpenFL. Erin Thacker left the LF and I am not clear whether this was in your queue or not. OpenFL GitHub is: https://github.com/intel/openfl
> 
> @jzcardoso OpenFL's new GitHub is https://github.com/securefederatedai/openfl
> 
> > @ibrahimhaddad Can you also verify if the following was completed:
> > 
> > * [ ]   (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
> > * [ ]   (Tech/ED) Migrate code repository to new GH org
> 
> @jzcardoso I sent invitations to these two accounts (thelinuxfoundation and ibrahimhaddad), but they did not accept yet.

I've noted the updated github.

And thanks for confirming the invites were sent.

**Comment by jzcardoso** [comment]
> I will add it to my queue. I have a few projects in queue before this so it might be a few days or a week or so.

Please note the updated github: https://github.com/securefederatedai/openfl

**Comment by jeffcshapiro** [comment]
Intake scan complete, report sent via email

**Comment by NSouthernLF** [comment]
Filed trademark and contribution agreement just now for ECN filing
