### ISSUE TITLE
DocArray Project Incubation Checklist - Sandbox to Incubation

### ISSUE THREAD

**Issue by redenmartinez** [lfai/foundation#58]
The following tasks are required to complete for projects which have moved from the Sandbox level to Incubation level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:** DocArray Project
**--Proposal URL:** [URL to Incubation proposal](https://docs.google.com/presentation/d/18pyNb1bezvH8FOeu154cmUN9eP1HE3cK/edit#slide=id.p1)
**--Incubation Date:**July 27, 2023
**--Technical Lead Contact:** [Joan Fontanals Martinez](joan.fontanals.martinez@jina.ai)

**ITEMS TO COMPLETE**
- [x] Update project flag to Incubation on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=incubating) (will auto update Incubated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Incubation level + Update 'Learn More' section with Graduation date
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Incubation flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Incubation flag, if wiki space is used
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1DoYGXGn4R1103i8yEiF788Qj6Yzrt2Yts3SXgBZjW-g/edit#gid=0) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [x] Create CS ticket to update LF AI & Data Timeline with project graduation under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline)
- [x] Update [LF AI & Data Overview Deck](https://docs.google.com/presentation/d/1FGFbHmopmYUrMeH2pPeYTBaECM6MqV9qfaLcV85xu24/edit?usp=sharing) - Projects slide + Structure & Governance slide
- [x] Update LF AI & Data Overview Deck on [LF AI & Data GitHub](https://github.com/lfai/presentations)
