### ISSUE TITLE
Marquez Project Graduation Checklist (Incubation to Graduate)

### ISSUE THREAD

**Issue by redenmartinez** [lfai/foundation#61]
The following tasks are required to complete for projects which have moved from the Incubation level to Graduate level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:** Marquez
**--Proposal URL:**[URL to Graduation Proposal](https://drive.google.com/drive/folders/11f3RmG8nYyvdalsaCkg9nEXUsKARcRoT)
**--Graduation Date:** September 7. 2023
**--Technical Lead Contact:**[Willy Lulciuc](https://github.com/wslulciuc)

**ITEMS TO COMPLETE**
- [x] Include TAC Graduation item for voting in next Governing Board meeting
- [x] Update project flag to Graduated on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=graduated) (will auto update Graduated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Graduate level + Update 'Learn More' section with Graduation date
- [x] Update [TAC wiki](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=7733341#TechnicalAdvisoryCouncil(TAC)-MemberRepresentatives) with Graduated project + project lead info for TAC voting representation
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Graduate flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Graduate flag, if wiki space is used
- [x] Add project lead to [tac-private mailing list](https://lists.lfaidata.foundation/g/tac-private/members) for voting representatives
- [x] Send [welcome/info note](https://docs.google.com/document/d/138IK-pNccyFO11DzVN7tRkUaplzoNIgFJfPvnCzkREo/edit) to project lead
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [x] Create CS ticket to update LF AI & Data Timeline with new technical project under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline)
- [x] Update [LF AI & Data Overview Deck](https://docs.google.com/presentation/d/1zow5UOXJfKQo6ScaKa1xwy2elx4dJ6gpheoUROCrOPE/edit#slide=id.g1196bedbe6a_0_1375) - Projects slide + Structure & Governance slide
- [x] Update LF AI & Data Overview Deck on [LF AI & Data GitHub](https://github.com/lfai/presentations)
