### ISSUE TITLE
Onboarding Tracker for Monocle Project

### ISSUE THREAD

**Issue by NSouthernLF** [lfai/foundation#79]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Sandbox
**--Company Sponsor (Full Legal Name):** Okahu, Inc.
**--Jurisdiction of Incorporation:** USA
**--Address:** 494 Cypress St  Redwood City CA 94061
**--Project Sponsor Contact:** Prasad Mujumdar
**--Technical Contact:** Prasad Mujumdar
**--Legal Contact:**
**--TAC Sponsor:** Prasad Mujumdar
**--TAC/GB Approval Date:** 6/27/24
**--Project License:** Apache 2.0
**--Project Presentation:** [URL](https://drive.google.com/file/d/1wmQ_zxBB5B_5bjG5nBGYmkGlWn13r6bp/view?usp=share_link) to presentation
**--Project Proposal per LF AI & Data:**  [URL](https://github.com/lfai/proposing-projects/blob/master/proposals/monocle-proposal.adoc) to proposal.
**--Project Artwork:** https://github.com/lfai/artwork/tree/main/projects/monocle

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The technical charter is tailored for LF AI & Data - Copy is to be created for each project - The technical charter will always need the following information dropped in place: the short name of the project (where [Community Name] appears); a short mission statement following the "The mission of the project is to..." convention; and confirmation of the specific licenses in Section 7 for code and/or data (many projects will not need data and this subjection regarding data licensing in those cases can be removed)
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The trademark assignment agreement is also tailored for LF AI & Data - Copy is to be created for each project - As for the trademark agreement, we will entertain changes from companies contributing projects but we ask that the following be made clear to project sponsors: the contribution agreement was prepared to be a balanced agreement -- A large number of our members sign this as drafted; and extensive comments and revisions to the agreement will involve time which will slow down a project's start with LF AI & Data
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (passing) ticket has been started + add ticket to this issue for reference -Project will be responsible for ensuring completion as per hosted project requirements // ** https://www.bestpractices.dev/en/projects/9176**

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // If logos exist post to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // got monocle2ai.org redirecting to GH right now
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [ ] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to LFX Onboarding tab of LF AI & Data PM Tracking spreadsheet (https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=2061542378)
- [x] (PM) Speak to project lead about project's need for AWS credits and document this in the LF AI & Data PM Tracking spreadsheet.
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki](https://wiki.lfaidata.foundation/). Get the project description from LFX. 
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist **pending Ibrahim - he indicated that he will send this**
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project 
- [x] (PM) Set up project in LFX Insights by adding project repo name to Source Control under Development and then adding connection in LFX Insights under LFX Tools
- [x] (PM) Set up project in LFX Security by ensuring that the security bot is installed in project GitHub repo, once that is confirmed, add connect the repo in LFX Security
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Verify project is added to [Project Website Access](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) tracking + verify all information is added per details under "Project Assets" section in this issue
- [x] (PM) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing)

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201265796032457/1202119631285769)) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201187889631310/1202119643716344
))
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through legal - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm Export Control Notice (ECN) filings are completed through legal via ticket at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2 (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by NSouthernLF** [comment]
added [pmujumdar](https://github.com/pmujumdar) - waiting for him to accept the github invite. then we'll add him to the issue.

**Comment by NSouthernLF** [comment]
@jeffcshapiro we need your help with this getting the intake and fossology scans set up.

**Comment by jeffcshapiro** [comment]
@NSouthernLF Sure, no problem.  I have the other project to do first, will either do this one at the same time or early next week.

**Comment by NSouthernLF** [comment]
Emailed Prasad to set up an onboarding call with him - also requested the names of the project leads to make sure we have accurate info (technical, legal, etc.)

**Comment by NSouthernLF** [comment]
@cakerly-lf we need your help completing the three marketing items above.

**Comment by jeffcshapiro** [comment]
intake license scan report email sent

**Comment by prasad-okahu** [comment]
Best Practices OpenSSF badge process ticket - https://www.bestpractices.dev/en/projects/9176

**Comment by prasad-okahu** [comment]
> added [pmujumdar](https://github.com/pmujumdar) - waiting for him to accept the github invite. then we'll add him to the issue.
@NSouthernLF, I looked at it pretty late. I suspect the invite is expired. Could you please resend the invite. Apologies for missing it.

**Comment by NSouthernLF** [comment]
HI Prasad

I just resent.

**Comment by NSouthernLF** [comment]
@cakerly-lf these three marketing items still need to be done. thanks.

**Comment by NSouthernLF** [comment]
AWS none needed

**Comment by NSouthernLF** [comment]
No additional collaboration tools needed.

**Comment by NSouthernLF** [comment]
No wiki needed 7/16/24

**Comment by NSouthernLF** [comment]
Emailed Prasad per his request to ask for administrative access to Linkedin and slack channel for the team.

**Comment by NSouthernLF** [comment]
Spoke with Jen Shelby to initiate design/execution of Monocle wordpress site per conversation with Prasad yesterday.

**Comment by NSouthernLF** [comment]
7/22/24 - Messaged Prasad again for an update on the charter and copied Ibrahim and Nancy.

**Comment by NSouthernLF** [comment]
Escalated request for ECN filing as this has not yet been completed by the support desk.

**Comment by jeffcshapiro** [comment]
@NSouthernLF Re: ECN filings, with the recent changes to JIRA queues across LF, there have been issues with my access to the ECN queue.  It may be a while before I can take care of the pending ECN requests, I will follow up with you later to make sure they are all sent.

**Comment by NSouthernLF** [comment]
Final signed charter received 8/14/24

**Comment by NSouthernLF** [comment]
Requested Github ownership from Prasad via email on 8/15/24 - to connect LFX Insights and Security. Awaiting a response.

**Comment by cakerly-lf** [comment]
> @cakerly-lf these three marketing items still need to be done. thanks.

All marketing items are now complete. Thank you!

**Comment by NSouthernLF** [comment]
ECN Filed
