### ISSUE TITLE
Onboarding Tracker for vLLM project

### ISSUE THREAD

**Issue by NSouthernLF** [lfai/foundation#80]
The following tasks are required to complete onboarding for an Incubation level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

**--Maturity Level Proposed:** Incubation
**--Company Sponsor (Full Legal Name):** University of California Berkeley
**--Jurisdiction of Incorporation:** USA
**--Address:**  2030 Addison Street, Berkeley, California 94704
**--Project Sponsor Contact:** Ion Stoica
**--Technical Contact:** Simon Mo
**--Legal Contact:**
**--TAC Sponsor:** Ion Stoica
**--TAC Approval Date:** 7/11/24
**--Project License:** Apache 2.0
**--Project Presentation:** [URL](https://github.com/vllm-project/vllm) to presentation
**--Project Proposal per LF AI & Data:** n/a
**--Project Artwork:** https://github.com/lfai/artwork/tree/main/projects/vLLM

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The technical charter is tailored for LF AI & Data - Copy is to be created for each project - The technical charter will always need the following information dropped in place: the short name of the project (where [Community Name] appears); a short mission statement following the "The mission of the project is to..." convention; and confirmation of the specific licenses in Section 7 for code and/or data (many projects will not need data and this subjection regarding data licensing in those cases can be removed)
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The trademark assignment agreement is also tailored for LF AI & Data - Copy is to be created for each project - As for the trademark agreement, we will entertain changes from companies contributing projects but we ask that the following be made clear to project sponsors: the contribution agreement was prepared to be a balanced agreement -- A large number of our members sign this as drafted; and extensive comments and revisions to the agreement will involve time which will slow down a project's start with LF AI & Data
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (Silver) ticket has been started + add ticket to this issue for reference -Project will be responsible for ensuring completion as per hosted project requirements / ** https://www.bestpractices.dev/en/projects/9249**

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // If no logo exists, request creation via Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) (All versions required: horizontal, vertical, icon in black/white/color in PNG and SVG)
- [x] (Tech/ED) Post project logos to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // If no domain is registered, then one is to be purchased // If one exists, it must be transferred using https://jira.linuxfoundation.org/servicedesk/customer/kb/view/28485232 // Reference: https://confluence.linuxfoundation.org/display/LID/Domain+Registration+and+Transfers  **pending vLLM team's completion of transfer ticket - filed 8/1/24**
- [x] (Tech/ED) Project website confirmation // If no website exists (as noted above), request a new website creation via Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) (Include request for project lead to be added as authorized user for Word Press for future website updates, requires -name/email of authorized user) 
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED) Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects) // n/a no proposal was submitted
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki
](https://wiki.lfaidata.foundation/)
- [x] (PM) Add project to LFX Onboarding tab of LF AI & Data PM Tracking spreadsheet - fill out all columns (https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=2061542378)
- [x] (PM) Speak to project lead about project's need for AWS credits and document this in the LF AI & Data PM Tracking spreadsheet.
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any
- [x] (PM) Set up project to utilize LFX Meetings as applicable/upon request
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project 
- [x] (PM) Set up project in LFX Insights by adding project repo name to Source Control under Development and then adding connection in LFX Insights under LFX Tools
- [x] (PM) Set up project in LFX Security by ensuring that the security bot is installed in project GitHub repo, once that is confirmed, add connect the repo in LFX Security
- [x] (PM) Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Verify project is added to [Project Website Access](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) tracking + verify all information is added per details under "Project Assets" section in this issue
- [x] (PM) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing)

**GOVERNANCE**

- [x] (PM) Help coordinate initial kickoff TSC/project meeting, if needed (TAC sponsor should be involved) 

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201265796032457/1202119631285769)) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201187889631310/1202119643716344
))
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824)
- [x] (Mktg) Add project spotlight for future publishing in internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824)
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through legal - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm Export Control Notice (ECN) filings are completed through legal via ticket at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2 (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by NSouthernLF** [comment]
@jeffcshapiro this needs intake and foss scans set up. thanks.

**Comment by jeffcshapiro** [comment]
@NSouthernLF I should be able to do this next week, although I do have a lot of pending intake scans for other project so it could be a bit longer - let me know if there is any schedule urgency.

I don't see an entry in your tracking spreadsheet yet, let me know when you've added it there.

**Comment by NSouthernLF** [comment]
Thanks @jeffcshapiro - it was literally just approved yesterday so we're just now starting to onboard. Timing wise it would be helpful to get it done in the next 2-3 weeks. Doable?

**Comment by jeffcshapiro** [comment]
@NSouthernLF 2-3 weeks should be OK

**Comment by NSouthernLF** [comment]
Invited simon-mo, WoosukKwon and zhuohan123 to LFAI GH to add them to this issue.

Also: emailed Simon Mo as the chief contact to set up a 30m onboard call with him.

**Comment by NSouthernLF** [comment]
Landing page ticket submitted 7/22/24

**Comment by NSouthernLF** [comment]
@cakerly-lf we need your help on the 3 marketing items above. thanks.

**Comment by NSouthernLF** [comment]
Nathan and Nancy spoke at length with Simon Mo for 30m 7/30/24 and noted the following as part of onboard:

-the project is asking for AWS credits, as its monthly cloud costs total > $50k and they are looking to bring this down. Nancy sent them the application for this and we clarified that 50 is a large ask - will see what can be done. For now this has been updated in the onboarding spreadsheet and AWS above is marked done.

-The project needs no additional collaboration tools (marked done above)
-The project does not desire a wiki space at this time (marked done above)
-The project is not conducting public meetings at this time (only internal) but is interested in doing LFX meeting management with a public calendar once the charter is signed. For now this is left unchecked above.
-The project has one key social media platform - in the form of Twitter/X. Simon wishes to have an alias created, wants to be added, but prefers to specify the others via an email with Nathan. Nathan emailed him to ask for names/addresses 7/30/24, and added him to alias vllm-social@lfaidata.foundation.
-For now a Jira ticket has been filed extending CM/scheduler access to the whole vLLM team.

**Comment by NSouthernLF** [comment]
Emailed Simon, Woosuk and Zhuohan, sent them https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/create/144
And requested the transfer of the vllm.ai website 8/1/24

**Comment by NSouthernLF** [comment]
Simon wrote back today to indicate that their website transfer ticket has been filed.

**Comment by NSouthernLF** [comment]
Regarding charter: Nancy and Nathan spoke with Simon on 7/30 who estimated 3-4 weeks for finalization. it is working its way through their legal team.

**Comment by NSouthernLF** [comment]
No public meetings requested at this time.

**Comment by NSouthernLF** [comment]
Nancy Rausch followed up again with vLLM team on charter today 8/26/24.

**Comment by jeffcshapiro** [comment]
Intake license scan complete, report sent via email

**Comment by NSouthernLF** [comment]
thanks Jeff

**Comment by NSouthernLF** [comment]
10/21/24 - Emailed Simon Mo to request _thelinuxfoundation_ ownership of Github and co-ownership extended to either Nancy or Nathan so that we can install LFX Insights and Security.

**Comment by NSouthernLF** [comment]
@cakerly-lf vLLM been finalized and the paperwork signed - so we need you to take care of the three above marketing items as an announcement when you get the opportunity. Thanks as always -N.

**Comment by NSouthernLF** [comment]
@narausch once Simon grants one of us temp GH access DCO still needs to be turned on. Thanks.

**Comment by NSouthernLF** [comment]
@ibrahimhaddad this needs a landscape update.

**Comment by ibrahimhaddad** [comment]
fully onboarded.
