### ISSUE TITLE
Onboarding Tracker for Ryoma Sandbox Project

### ISSUE THREAD

**Issue by NSouthernLF** [lfai/foundation#81]
The following tasks are required to complete onboarding for a Sandbox level project joining the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**TECHNICAL PROJECT DETAILS**

-Maturity Level Proposed: Sandbox
--Company Sponsor (Full Legal Name): AITA, Inc.
--Jurisdiction of Incorporation: United States
--Address: 934 Visconti Pl Santa Clara, CA 95050 US
--Project Sponsor Contact: Hao Xu ([sduxuhao@gmail.com](mailto:sduxuhao@gmail.com))
--Technical Contact: Hao Xu ([sduxuhao@gmail.com](mailto:sduxuhao@gmail.com))
--Legal Contact:
--TAC Sponsor: Hao Xu ([sduxuhao@gmail.com](mailto:sduxuhao@gmail.com))
--TAC/GB Approval Date: 7/25/24
--Project License: Apache 2.0
--Project Presentation: [URL](https://docs.google.com/presentation/d/17YN_3laaJwhs-nrXjt6fyPvp5rQJG7ez/edit?usp=share_link&ouid=112783960678330199246&rtpof=true&sd=true) to presentation
--Project Proposal per LF AI & Data: [URL](https://github.com/lfai/proposing-projects/blob/master/proposals/aita.adoc) to proposal
--Project Artwork: Logo: https://github.com/lfai/artwork/tree/main/projects/ryoma

**LICENSING**

- [x] (Tech/ED) Project license exists and is OSI-approved 
- [x] (Tech/ED) Proposed license inline with umbrella's IP Policy 
- [x] (Tech/ED) Pre-intake FOSSology scan complete, shared with project, and no major incompatible licenses detected
- [x] (Tech/ED) Determine known components/dependencies not under compatible license

**CONTRIBUTION**

- [x] (Tech/ED) Deactivation of CLA/DCO in place and adopt GitHub's DCO at https://github.com/apps/dco
- [x] (Tech/ED) Share/Discuss Project Charter Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The technical charter is tailored for LF AI & Data - Copy is to be created for each project - The technical charter will always need the following information dropped in place: the short name of the project (where [Community Name] appears); a short mission statement following the "The mission of the project is to..." convention; and confirmation of the specific licenses in Section 7 for code and/or data (many projects will not need data and this subjection regarding data licensing in those cases can be removed)
- [x] (Tech/ED) Share/Discuss Account & Trademark Assignment Template and Finalize with Project ([update New Projects Onboarding with Legal Status Tracking](https://docs.google.com/spreadsheets/d/1L7qsm80ge2lhaTKgzsOuKSwwL6VssoBil09aibqhnp0/edit?ts=5e7956f1#gid=0))
Note: The trademark assignment agreement is also tailored for LF AI & Data - Copy is to be created for each project - As for the trademark agreement, we will entertain changes from companies contributing projects but we ask that the following be made clear to project sponsors: the contribution agreement was prepared to be a balanced agreement -- A large number of our members sign this as drafted; and extensive comments and revisions to the agreement will involve time which will slow down a project's start with LF AI & Data
- [x] (Tech/ED) Verify [OpenSSF Best Practices Badge](https://bestpractices.coreinfrastructure.org/en) (passing) ticket has been started + add ticket to this issue for reference -Project will be responsible for ensuring completion as per hosted project requirements

**PROJECT ASSETS**

- [x] (Tech/ED) Logos confirmation // If logos exist post to [GitHub Artwork repo](https://github.com/lfai/artwork/tree/master/projects) and save in Project Logos in [LF internal Google Drive folder](https://drive.google.com/drive/folders/1B8NQV40vpd1sSLEBJempN2u3RLJFQKHy)
- [x] (Tech/ED) Domain name confirmation // If one exists, it must be transferred using https://jira.linuxfoundation.org/servicedesk/customer/kb/view/28485232 // Reference: https://confluence.linuxfoundation.org/display/LID/Domain+Registration+and+Transfers 
- [x] (Tech/ED) Project website tracking // Add link and name/email of authorized user for website to [LF internal tracking](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) 
- [x] (PM) Include project .svg logo in Project Definition section of PCC.

**TAC & GOVERNING BOARD REVIEW**

- [x] (Tech/ED) Provide project proposal process/template to project sponsor (https://github.com/LFDLFoundation/proposing-projects/tree/master/proposal-process)
- [x] (Tech/ED) Confirm/Schedule presentation date during TAC meeting - Add to [TAC Mtg Agenda Tracking](https://docs.google.com/spreadsheets/d/1uJD0zXFTXaYrROY5RWHbK7C3T6J1VMF_BXqY5aRaqec/edit#gid=0)
- [x] (Tech/ED) Review and confirm final proposal and presentation deck
- [x] (Tech/ED) Add project presentation to TAC agenda/deck and send to tac-general mail list with agenda info
- [x] (Tech/ED)Send project presentation and proposal to tac-private mail list with reminder on attendance and quorum requirements for voting members
- [x] (PM) Verify TAC minutes with project TAC vote results

**INFRASTRUCTURE**

- [x] (Tech/ED) Update proposal to show project accepted in [GitHub Project List](https://github.com/lfai/proposing-projects)
- [x] (Tech/ED) Setup org in Github, add 'thelinuxfoundation' as an owner - Allows us to maintain continuity of GH ownership
- [x] (Tech/ED) Migrate code repository to new GH org
- [x] (Tech/ED) Add project to [LF AI & Data Landscape](https://landscape.lfai.foundation/) and mark it as an LF AI & Data project

**OPERATIONS**

- [x] (PM) Add project technical lead contact info (name/email) to [internal tracking](https://docs.google.com/spreadsheets/d/1gonSD_YgJY8-0COpoR1fPIVFGOmf-fajfL_qWmLZBjI/edit#gid=0) 
- [x] (PM) Post final technical charter to [GH Project Charters repo](https://github.com/lfai/foundation/tree/master/technical%20project%20charters) and ensure it is saved in [LF internal Projects Google Drive folder](https://drive.google.com/drive/u/0/folders/1rcgzNxHJzbM4KmULpbtIpXiK2Zmt62Ei)
- [x] (PM) Add project to LFX Onboarding tab of LF AI & Data PM Tracking spreadsheet - fill out all columns (https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=2061542378)
- [x] (PM) Speak to project lead about project's need for AWS credits and document this in the LF AI & Data PM Tracking spreadsheet.
- [x] (PM) Add project to Current Projects section on [LF AI & Data wiki](https://wiki.lfaidata.foundation/). Get the project description from LFX. 
- [x] (PM) Set up other misc collaboration tools agreed upon during proposal/acceptance, if any
- [x] (PM) Set up project mail lists (announce, tsc, technical-discuss, security) under [LF AI & Data Groups.io](https://lists.lfaidata.foundation/groups)
- [x] (PM) Add initial project lead(s) to applicable mail lists (main, announce, events, tac-general, project mail lists, technical-projects)
- [x] (PM) Set project lead as moderator for mail lists as applicable for ongoing management
- [x] (PM) Add LF AI & Data marketing manager to project announce mail list as moderator for sending announcements
- [x] (PM) Send[ onboarding email](https://docs.google.com/document/d/1E1MdDwo_6KN7uJ11xqpFW_ATtgGggZCsNo8ML9g-mSI/edit) with next steps info and resources - Includes Technical Getting Started Checklist
- [x] (PM) Set up project wiki space under LF AI wiki - Upon request only per onboarding email info provided to project 
- [x] (PM) Set up project in LFX Insights by adding project repo name to Source Control under Development and then adding connection in LFX Insights under LFX Tools
- [x] (PM) Set up project in LFX Security by ensuring that the security bot is installed in project GitHub repo, once that is confirmed, add connect the repo in LFX Security
- [x] (PM)Share new project update w/Outreach Committee (Chair) to include in upcoming committee meeting 
- [x] (PM) Include update on new project in upcoming GB meeting agenda
- [x] (PM) Verify project is added to [Project Website Access](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=503900668) tracking + verify all information is added per details under "Project Assets" section in this issue
- [x] (PM) Transfer social account domain ownership to LF AI & Data shared account use set up, if applicable - Projects retain ongoing management of accounts - Reference [internal process documentation](https://docs.google.com/document/d/1ixOge5XZzm3uzEoAgHrOKBpNtNIgSHxCvEzd0agrUB0/edit?usp=sharing)

**MARKETING**

- [x] (PM) Update LF AI & Data Timeline with new project - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201265796032457/1202119631285769)) - Save updated file in internal [LF AI & Data G Drive](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA) and on [LF AI & Data GH](https://github.com/lfai/presentations/tree/master/timeline-graphic)
- [x] (PM) Build landing page on LF AI & Data website and add to [All Projects section](https://lfaidata.foundation/projects/) - Creative Services [Asana ticket](https://www.linuxfoundation.org/marketing-requests) required ([Reference](https://app.asana.com/0/1201187889631310/1202119643716344
))
- [x] (Mktg) Coordinate announcement (press release or blog post) and social promotion with project company - Add to internal [LF AI & Data PR/Comms tracker](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824) - Sandbox projects are announced via social followed by blog announcement on a quarterly basis
- [x] (Mktg) Follow project and member company on Twitter/LinkedIn from LF AI & Data accounts, if applicable
- [x] (Mktg) Publish announcement (Blog/PR+Social+Mail Lists)

**LEGAL FOLLOW UP**

- [x] (PM) Confirm ongoing license scanning is set up through legal - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=192619434)
- [x] (PM) Confirm Export Control Notice (ECN) filings are completed through legal via ticket at https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2 (trademark/contribution agreement + website needed for filing request via Legal Jira ticket ) + Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1584923649) for future scans planned through Software Freedom Law Center for Graduate level projects
- [x] (PM) Include all projects in Trademark Registrations review cycles - Graduate level projects addressed at start of each calendar year - Add to internal [LF AI & Data tracker](https://docs.google.com/spreadsheets/d/1cJ-rRNaklYGu_JyvQwBUwRJWXlIDA0VkGG7Hcyw-h00/edit#gid=1479617876)

**Comment by NSouthernLF** [comment]
@jeffcshapiro still early - this one is in process (it was renamed Delmar from Aita) so they are just now getting their new Github setup. Once they do it will need intake scans in the next few weeks. Thanks.

**Comment by NSouthernLF** [comment]
Asana logo ticket filed with instructions to consult with Hao on the design; mailing list names updated groups.io and pcc; internal tracking and onboarding sheets updated with new project name Ryoma.

**Comment by NSouthernLF** [comment]
Tue 8/6/24 - Hao Xu approved the charter in an email thread. We are currently waiting for legal/formation at LF to approve

**Comment by NSouthernLF** [comment]
Wed. 8/14/24 Design submitted a logo for Ryoma to Hao Xu's team, via email. We are awaiting their final approval of the design.

**Comment by NSouthernLF** [comment]
Final signed charter received 8/14/24

**Comment by NSouthernLF** [comment]
LFX Security added. Community Manager set up. Waiting for integrations build to onboard insights later this afternoon. Hao Xu added as project lead - community manager/scheduler in PCC

**Comment by NSouthernLF** [comment]
Insights onboarded.

**Comment by NSouthernLF** [comment]
ECN Export Control notices filed https://jira.linuxfoundation.org/browse/IT-27106

**Comment by NSouthernLF** [comment]
Ticket filed for new Ryoma landing page on LF AI & Data projects page 8/20/24

**Comment by NSouthernLF** [comment]
No AWS credits needed at this time per call with Hao 8/20/24

**Comment by NSouthernLF** [comment]
No misc collaboration tools needed at this time per call with Hao 8/20/24

**Comment by NSouthernLF** [comment]
No social media accounts at this time per call with Hao 8/20/24. Project is in the process of setting them up. I set up the alias and advised Hao to use ryoma-social@lfaidata.foundation and to let us know when this has been done so we can store the passwords in 1pw. He agreed.

**Comment by NSouthernLF** [comment]
No public meetings at this time - Ryoma is in the process of setting them up and wishes to take advantage of the public calendar. I filed a jira ticket for PCC to give Hao Community Manager/Scheduling access.

**Comment by NSouthernLF** [comment]
Hao indicated that he wishes to have project-ryoma.com registered, so we set it up through PCC 8/20/24.

He also agreed to move ahead with DCO

-The Project is starting its openSSF badge process immediately.

**Comment by NSouthernLF** [comment]
@jeffcshapiro how is this looking for an intake scan?

**Comment by jeffcshapiro** [comment]
@NSouthernLF I will take care of it early next week.  Is this project already in your tracking spreadsheet?

**Comment by NSouthernLF** [comment]
@jeffcshapiro yes it is.

**Comment by NSouthernLF** [comment]
@cakerly-lf the marketing announcements on this still need to be done. thanks.

**Comment by HaoXuAI** [comment]
@NSouthernLF I didn't receive the Community Manager/Scheduling access, do you mind sending it to me again? Also when are going to have the www.project-ryoma.com ready to use? thanks!

**Comment by NSouthernLF** [comment]
Best practices badge has been started per OpenSSF lookup. Marking this 'done.'

**Comment by NSouthernLF** [comment]
@jeffcshapiro how is this looking wrt the intake scan?

**Comment by NSouthernLF** [comment]
DCO is installed and turned on. marking this done.

**Comment by jeffcshapiro** [comment]
@NSouthernLF will try to get to it by Friday

**Comment by NSouthernLF** [comment]
thank you

**Comment by jeffcshapiro** [comment]
@NSouthernLF Sorry for the delay, I've been finishing some other high priority projects.  Will get to this next week and will take care of all pending LFAI intake scans.

**Comment by jeffcshapiro** [comment]
Intake scan complete and report sent via email
