### ISSUE TITLE
Tracker for Bitol Graduation (Sandbox>Incubation)

### ISSUE THREAD

**Issue by NSouthernLF** [lfai/foundation#85]
The following tasks are required to complete for projects which have moved from the Sandbox level to Incubation level within the LF AI & Data Foundation. LF Staff will engage with the technical project lead via this issue and work through the checklist to completion. 

LF AI & Data Staff: Review each item, confirm completion, and add any relevant notes.

Note: (ED) Executive Director, (Tech) Technical Lead, (PM) Program Management & Operations Lead, (Mktg) Marketing Lead

**PROJECT INFORMATION**

**--Project Name:**
**--Proposal URL:**
**--Graduation Date:**
**--Technical Lead Contact:**

**ITEMS TO COMPLETE**
- [x] Update project flag to Incubation on [LF AI & Data Landscape](https://landscape.lfai.foundation/card-mode?project=incubating) (will auto update Incubated Projects on LF AI & Data website)
- [x] Update [project landing page on LF AI & Data website](https://lfaidata.foundation/projects/) to reflect Incubation level + Update 'Learn More' section with Graduation date
- [x] Update [LF AI & Data wiki](https://wiki.lfaidata.foundation/) project list with Incubation flag
- [x] Update project space homepage on [LF AI & Data wiki ](https://wiki.lfaidata.foundation/)with Incubation flag, if wiki space is used
- [x] Add graduation announcement to [LF AI & Data PR/Comms Tracking](https://docs.google.com/spreadsheets/d/1x1XoyodXcrp1DTlLpr_wVDJA-3DPsJu5-2q0MIIiAAo/edit#gid=279628824) to begin announcement prep (note CS ticket needed for social media image) + Flag Marketing Manager for coordination
- [x] Create CS ticket to update LF AI & Data Timeline with project graduation under month accepted + [Save in Google Drive ](https://drive.google.com/drive/u/0/folders/10CQl3ia2wftbZOhBfy4lS-HaKT8i4cOA)+ [Update on GitHub](https://github.com/lfai/presentations/tree/master/Timeline)

**Comment by NSouthernLF** [comment]
@ibrahimhaddad please update landscape when you get the chance. thanks.
